### ISSUE TITLE
CI with Travis or CodeCov

### ISSUE THREAD

**Issue by paulmolluzzo** [kentcdodds/glamorous-website#10]
This is a chore for @kentcdodds I think:

We should set up Travis or CodeCov to have automated testing for PRs.

**Comment by kentcdodds** [comment]
Yeah, that would be very helpful. Especially this: https://github.com/zpnk/stage-ci

**Comment by kentcdodds** [comment]
Sorry. I've been busy. I activated travis on the repo so we should be good to just add a `.travis.yml` and have it work. Codecov will work out of the box. Just need to start sending stuff.

**Comment by paulmolluzzo** [comment]
Handled this with #15.
