### ISSUE TITLE
Country flags for Localization 

### ISSUE THREAD

**Issue by jonmajorc** [kentcdodds/glamorous-website#102]
What you did:
Stay relevant on Twitter... 🙃

What happened:
mentioned @kentcdodds and @paulmolluzzo and conversation happened... 😏

Suggested solution:
This cool repo we can use for [country flags](https://github.com/hjnilsson/country-flags) with localization dropdown

**Comment by kentcdodds** [comment]
Could probably use some designs on this :)

**Comment by jonmajorc** [comment]
My son was just born, so I won't be able to focus my time much right now 😄  

I did find in my research [Webpack](https://webpack.js.org/) does it best! I would use that has a reference 😃

**Comment by paulmolluzzo** [comment]
@jonmajorc 🎉🎉🎉🎉 Congrats! Enjoy the time with your baby and get off the computer!

**Comment by tdeschryver** [comment]
Maybe a stupid question, but do we really need this?
When starting on the implementation I asked myself which country flags I should use for the locales, for some inspiration I went looking at some sites which are already being mentioned here and there.
And none of these websites are doing this: [Jest](https://facebook.github.io/jest/), [webpack](https://webpack.js.org/), [styled-components (only en)](https://www.styled-components.com/docs/basics).

If its needed I guess we'll go for the most obvious flags (USA, Spain, France).

**Comment by kentcdodds** [comment]
I wonder if it could be offensive to get the country wrong or something... Hmmm....

**Comment by paulmolluzzo** [comment]
I don't think it would be offensive as it's fairly common practice to use the French flag for designating French and Spain for Spanish. Occasionally you do see English designated by an icon that's half U.K. and half USA, but AFAIK that's less about being politically correct and more about UX.

Keep in mind we're not designating locales, just language, so again a simple designation is generally acceptable.

**Comment by tdeschryver** [comment]
I played around with this for a bit and came up with this, thoughts?
![image](https://user-images.githubusercontent.com/28659384/27507900-178a0c36-58da-11e7-8c0d-2a731f0ac1f7.png)

Or with full names:
![image](https://user-images.githubusercontent.com/28659384/27507918-6c0b7380-58da-11e7-9f25-a9f8cb9e5045.png)

**Comment by paulmolluzzo** [comment]
I like the full word better. Just to be sure, "Help Translate" will be printed in the currently selected language, right?

**Comment by tdeschryver** [comment]
Correct @paulmolluzzo! (it still is using the content files)

**Comment by tdeschryver** [comment]
Decreased the font size, aligned to left, added a border and added an hover background. 
Should I create a PR for this?

![image](https://user-images.githubusercontent.com/28659384/27535616-f4571996-5a6b-11e7-861f-5e82cba6827e.png)

**Comment by kentcdodds** [comment]
Yes, that looks great!
