### ISSUE TITLE
Don't alias until the deploy is finished

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#103]
**Problem Description:**

Every time we merge into master, a build is kicked off and we automatically deploy the new version. Unfortunately that means that people using the site will see this:

![screen shot 2017-06-12 at 10 27 09 am](https://user-images.githubusercontent.com/1500684/27044143-d03040c8-4f59-11e7-9ec4-e798c2b8be05.png)

Not super awesome.

**Suggested Solution:**

It would be better if we waited to alias the site to the deployment until _after_ the deploy/build is successful and ready to take on traffic. Any ideas?

**Comment by paulmolluzzo** [comment]
On mobile so this is super basic idea, but maybe we can check the status on an interval and check for the `READY` status on the `id` we deployed. I'm thinking that where we're doing the alias we can use a 1 minute interval (or 5 to avoid rate limiting?) then alias if it's ready and kill the interval.

https://zeit.co/api#get-endpoint

Sorry for the brevity.

**Comment by kentcdodds** [comment]
Sounds like that's something we'll have to do. I wonder whether this is a solved problem 🤔

**Comment by sergiodxa** [comment]
@kentcdodds Have you tried with [now-pipeline](https://github.com/bahmutov/now-pipeline)?

**Comment by kentcdodds** [comment]
That looks like exactly what we need. If course @bahmutov is behind it 😉 that guy is awesome!

**Comment by kentcdodds** [comment]
Thanks for mentioning it!

**Comment by sholladay** [comment]
I need this as well. And for me, an added wrinkle is that many of my apps initialize asynchronously - usually connecting to a database or similar. So they are not ready immediately after the process launches.

Some examples of how other technologies deal with this:

 - Kubernetes has the concept of a [readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/), basically polling for some arbitrary condition.
 - PM2 has [graceful start](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#graceful-start), a simple event-based convention where the worker sends a ready message to the parent process.

I like graceful start as it is very simple (see [app-ready](https://github.com/sholladay/app-ready) for an example). Some people use health check routes (like [hapi-hi](https://github.com/sholladay/hapi-hi)) for similar purposes. But even if Now simply waited until `server.listen()` was called, that would still be very useful.

**Comment by kentcdodds** [comment]
I'm thinking something more simple solution for now should suffice. When I `curl` a deploy URL that's currently building, I get back:

```
<!doctype html>
<!-- https://now.sh -->
<h1>Redirecting (302)</h1>
<a href="https://zeit.co/kentcdodds/glamorous-website/kdjqndzvgr?redirect=1">https://zeit.co/kentcdodds/glamorous-website/kdjqndzvgr?redirect=1 </a>
```

That should be easy enough to parse through to know that it's not yet ready. This way we don't need to worry about using the client or anything, we can just curl. We could start `curl`ing after about 10 minutes (because it takes at least that time every time). Then we can `curl` every 10 seconds or so. Maybe we could do up to 60 times (10 minutes). I think it should be pretty straightforward.

Thoughts?

**Comment by sholladay** [comment]
I just made [await-url](https://github.com/sholladay/await-url) for the polling strategy. Because JavaScript.

😇

**Comment by kentcdodds** [comment]
Oh my, that's just amazing! We could use that in [`alias.sh`](https://github.com/kentcdodds/glamorous-website/blob/master/other/alias.sh) 👍 anyone want to do that? Should be dead simple. Could even use [`npx`](http://nom.im/npx) which would be sweet!

**Comment by kentcdodds** [comment]
Ok, we've got this fixed. I have a local fork of `await-url` for now until https://github.com/sholladay/await-url/pull/1 is merged and released :)

Also async/await in Node 8 is awesome.

**Comment by sholladay** [comment]
`await-url@0.3.0` is out with the options fixes. I tweaked the default `interval` and `tries` values in the hopes of finding a better balance between reliability for this use case and failing within a reasonable amount of time if the URL is never going to come alive.

**Comment by kentcdodds** [comment]
Cool, thanks! Now if you have any ideas for how to deal with #126 I'd really appreciate it :)

**Comment by bahmutov** [comment]
`await-url` looks awesome, and could work nicely as the test command to `now-pipeline`. I have been using `now-pipeline` just recently in https://www.cypress.io/blog/2017/05/30/cypress-and-immutable-deploys/
