### ISSUE TITLE
Navigation is cut off for smaller screens

### ISSUE THREAD

**Issue by CarlRosell** [kentcdodds/glamorous-website#106]
**Problem Description:**
All the navigation links at the top are not visible on smaller screens.
<img width="280" alt="screen shot 2017-06-12 at 23 56 00" src="https://user-images.githubusercontent.com/2036823/27059154-5316dc56-4fd5-11e7-98db-30fab9f2808b.png">

**Suggested Solution:**
Maybe wrap the elements.

**Comment by kentcdodds** [comment]
Thanks @CarlRosell! We're working on updating the design a bit in #26, wanna chime in there? If you'd like you can go ahead and implement some of that :)

Thanks again! Closing this in favor of #26
