### ISSUE TITLE
Add in License, Contributing, Code of Conduct, etc

### ISSUE THREAD

**Issue by paulmolluzzo** [kentcdodds/glamorous-website#11]
We'd like to have this as a MIT licensed project, but there isn't any LICENSE file yet.

In addition, we should probably add a Contributing file and Code of Conduct.

Any other neat things we can think of (PR templates, commitzen, etc.) could be helpful too. Whatever makes it easy for people to contribute! 😄

**Comment by kentcdodds** [comment]
Yeah, I should have bootstrapped this project with my generator to get most of that stuff by default 😅 I'll get to that ASAP.

**Comment by paulmolluzzo** [comment]
Fixed in #15.
