### ISSUE TITLE
Fix HTML generated from markdown to be valid

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#114]
Got this email from Algolia:

Hi Kent,

I am having trouble creating the config for your doc.
The reason is that you have `<p>` tag inside titles like `<h1>`.
This is incorrect html, and the parser we are using (http://lxml.de/) is ignoring it completely.

Could you remove that on your side ?

**Comment by kentcdodds** [comment]
Anyone wanna investigate this?

**Comment by paulmolluzzo** [comment]
It's the documentation. Look at this line: https://github.com/kentcdodds/glamorous-website/blob/master/components/docs-page.js#L67

`{interactiveMarkdown(heading)}` is shoving a `<div><p>[content]</p></div>` inside the heading.

This is happening on all the headings actually. 😕

**Comment by paulmolluzzo** [comment]
https://github.com/kentcdodds/glamorous-website/blob/master/components/docs-page.js#L111

Maybe it should just be:
```js
 <h4/>{subtitle}</h4>
```

**Comment by kentcdodds** [comment]
But some of the titles are written in markdown. I've actually dealt with this before. [This](https://github.com/kentcdodds/kentcdodds.com/blob/2e6b14628efbd6c064f4bf38c680d2d307451772/src/utils.js#L71-L77) is what I did: 

```javascript
function markdownToHTML(string) {
  return marked(stripIndent(string))
}

function markdownToHTMLWithNoPTag(string) {
  return markdownToHTML(string).slice(3, -5)
}
```

We could probably do the same thing pretty easily...
