### ISSUE TITLE
Suggestion: Example code block on Homepage is too big/long

### ISSUE THREAD

**Issue by wcastand** [kentcdodds/glamorous-website#115]
**Problem Description:**

I think the code block in the homepage is way to big. Lot of unecessary stuff for glamorous.

When i see it, it feels like glamorous is more complex that it actually is and involve a lot of verbosity (which isn't).

You example is far too long and can't hold in my macbook's screen without scrolling :/

Overall, the site feels too big (fonts, logo, ...)

**Suggested Solution:**

I really like styled-component code block.
It's short, efficient, clear and can hold in my macbook screen without scrolling.

I think if we only style one button, it could make the homepage less "big" and more appealing to new comers.

```javascript
const Button = glamorous.a({
  border: '1px solid #F67982',
  textDecoration: 'none',
  borderRadius: 4,
  transition: 'all .3s',
  ':hover': {
    backgroundColor: ({primary}) => primary ? primary : 'white',
  }
})
```

**Comment by kentcdodds** [comment]
Agreed! I've had similar feelings. Let's shorten it 👍

**Comment by kentcdodds** [comment]
Thanks @wcastand!

**Comment by wcastand** [comment]
i made a issue for the nav and title/button on homepage :) #121
