### ISSUE TITLE
Improve fallback for translations

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#118]
Right now we only fallback to english if the translated file doesn't exist. Instead, we should merge the english version with the translated version just in case the translated version exists, but has empty strings for some values (is incomplete) or doesn't have some values at all. This fallback behavior happens [here](https://github.com/kentcdodds/glamorous-website/blob/4bc565a4ad3257d359c99f4cc8469b82d5cf38bc/components/locale.js#L65-L87).

**Comment by tdeschryver** [comment]
Is it OK if I'm taking this one?

**Comment by kentcdodds** [comment]
Yes please! Thanks!

**Comment by tdeschryver** [comment]
Just one quick question, does it make sense to 'replace' empty strings? In my opinion if its left blank, its done on purpose.

**Comment by kentcdodds** [comment]
I think that it does. In some cases it makes sense to have an empty string for localization, but not in this docs site. I can't think of a scenario I wouldn't want a string to appear in one locale. If it's really important, people can just set it to `null` and we could do a `null` check when doing the merge maybe...

**Comment by kentcdodds** [comment]
Thanks @tdeschryver!
