### ISSUE TITLE
Use React Live?

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#12]
I'm pretty sure this is what Styled-Components uses for their site: https://react-live-demo.philpl.com/

**Comment by paulmolluzzo** [comment]
Yes! Let's do that!

**Comment by paulmolluzzo** [comment]
I was thinking, this is a fantastic way to show examples, but I wouldn't even know where to put them on the site. 😀

What do we want to put in the guides vs what goes in the examples? I'm not sure what the difference is.

I was thinking that this would be good for guides that _are_ examples, and they're live with `react-live`. We can do a guide on making a custom component, extending a component, using `props`, and using a theme and `themeProvider`, to name a few.

If we do this we'd just have guides and documentation really. Is that sensible?

**Comment by kentcdodds** [comment]
Let's do that, but add an "Integrations" section for stuff like polished, next, etc.

**Comment by paulmolluzzo** [comment]
Started working on this for the home page. It's also setting up the components and whatnot for all the examples. Look for something tonight.

**Comment by paulmolluzzo** [comment]
😍  https://glamorous-website-pr-improve-homepage.now.sh/
