### ISSUE TITLE
Move the nav menu and maybe the Title/logo/button on the homepage

### ISSUE THREAD

**Issue by wcastand** [kentcdodds/glamorous-website#121]
**Problem Description:**

As discussed in #117 
The nav is weirdly aligned right now, it would be better centered or all the way to the right/left.
If we can make more size and simplify the homepage or reduce the size of the title/logo.

**Suggested Solution:**

Move the nav to the right/left or center it and move the button to make more size on homepage.
styled-component's website is a good example of simplicity i think.

**Comment by forresst** [comment]
Would it be possible at the same time to make the menu titles translatable (`Basics`, `Advanced`, `Examples`, `Integration` and `API`)?

**Comment by kentcdodds** [comment]
Ah! Yes, we should definitely do that as well! Let's make a new issue for that one.

**Comment by kentcdodds** [comment]
I've opened up this: https://github.com/kentcdodds/glamorous-website/pull/188

Feedback/reviews appreciated!
