### ISSUE TITLE
Update CONTRIBUTING.md to reflect removal of commitizen from nps scripts

### ISSUE THREAD

**Issue by mwickett** [kentcdodds/glamorous-website#127]
**Problem Description:**
Looks like commitizen was removed.

I had just gotten the hang of using `npm start commit` to commit. When committing for a PR, should I still follow the same approach? :)

Happy to update `CONTRIBUTING.md` once I'm sure of the procedure for commit messages.

**Comment by kentcdodds** [comment]
Yeah, let's remove that, thanks!

**Comment by kentcdodds** [comment]
Oh, and I don't care about commit message format in this repo 🙃
