### ISSUE TITLE
Add contributors to each page

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#129]
I love how [webpack's docs](https://webpack.js.org/configuration/devtool/) has avatars of those who contributed to the docs on that page. Someone wanna figure out how they do that and add that to our site?

<img width="605" alt="screen shot 2017-06-13 at 10 06 49 pm" src="https://user-images.githubusercontent.com/1500684/27114969-a373e8a6-5084-11e7-8bd6-a417396b028c.png">

**Comment by tdeschryver** [comment]
Seems like they are putting the contributors in the [content files](https://github.com/webpack/webpack.js.org/blob/master/content/development/index.md) (these are markdowns). 
In the [page layout file](https://github.com/webpack/webpack.js.org/blob/master/components/page/page.jsx#L63) these contributors are being passed to a [contributor component](https://github.com/webpack/webpack.js.org/blob/master/components/contributors/contributors.jsx).

I think we can extend our content files with a contributors array and 'inject' them somewhere central, maybe in [file.js](https://github.com/kentcdodds/glamorous-website/blob/master/components/locale.js) (and of course create a contributors component)?

**Comment by kentcdodds** [comment]
Perfect! Thanks for looking into it @tdeschryver! We could add that easily enough! Anyone wanna take on the challenge?

**Comment by tdeschryver** [comment]
So this is a bit out of my comfort zone, but I gave it a shot.

![contributors](https://user-images.githubusercontent.com/28659384/27195488-3c8f8b3e-5207-11e7-83c0-0011df8e3d27.PNG)

**Comment by kentcdodds** [comment]
Looks excellent! Let's see a pull request and we can give you some pointers 😀

**Comment by paulmolluzzo** [comment]
Closed by #148
