### ISSUE TITLE
Make a fun badge for contributors to tweet out

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#133]
I just saw [this](https://twitter.com/igor_randj/status/874941696307593216):

<img width="645" alt="screen shot 2017-06-14 at 6 24 23 am" src="https://user-images.githubusercontent.com/1500684/27131930-23beb5dc-50ca-11e7-8e0e-f81ee828bedc.png">

And it gave me an idea. What if we made something like that for folks to tweet out after they've contributed to the glamorous.rocks website? It could say:

- I just contributed translations to glamorous.rocks! Want to try too?
- I just contributed code to glamorous.rocks! Want to try too?
- I just contributed an example to glamorous.rocks! Want to try too?

And the tweet could have a link to the contributing guidelines or something.

The goal behind this is twofold:

1. Express gratitude to contributors
2. Encourage new contributors

I'm open to any other ideas :)

**Comment by paulmolluzzo** [comment]
Love this idea! Do we even have #21 done yet? It's really just a regular tweet message and the rest is handled by that card.

**Comment by kentcdodds** [comment]
#21 isn't quite done, but I was thinking doing something similar. What if we had a contributing page that could dynamically choose the twitter image based on a query string? Something like:

```
https://glamorous.rocks/contribute?type=translation
https://glamorous.rocks/contribute?type=site
https://glamorous.rocks/contribute?type=core
```

I think that would be doable :+1:

Could use @jonmajorc's skills here ;-)
