### ISSUE TITLE
CONTRIBUTING.md - incorrect command

### ISSUE THREAD

**Issue by irth** [kentcdodds/glamorous-website#147]
**Problem Description:**
CONTRIBUTING.md states
> This project uses nps and you can run npm start to see what scripts are available.

`npm start` tries to serve the website (and expects it to be built - which makes it fail on a freshly cloned repos)

It tells the user that it couldn't find `.next/build-stats.json`, which isn't a great first experience ;)
![x](https://user-images.githubusercontent.com/1735193/27195153-eac72268-5205-11e7-9c80-a9ed7a06c9d6.png)

**Suggested Solution:**
Change the `npm start` to `npm start help` which does show a list of scripts.
![x](https://user-images.githubusercontent.com/1735193/27195189-0ae08026-5206-11e7-8e48-88d1dd614645.png)

Additionaly, the [Working with locales](https://github.com/kentcdodds/glamorous-website/blob/master/CONTRIBUTING.md#working-with-locales) section could use a 
```
monospace block thingy
```
on the host file contents.

I am willing to do a PR for both of those problems, should it be a single pull request or two separate?

**Comment by kentcdodds** [comment]
Thanks! You can make a single pull request for both, that's fine 😀
