### ISSUE TITLE
Interactive tutorial for beginners

### ISSUE THREAD

**Issue by bernard-lin** [kentcdodds/glamorous-website#156]
An interactive tutorial for beginners learning css-in-js with glamorous inspired by Kye Hohenberger https://twitter.com/tkh44/status/875768337061617664 

I'll be taking a stab at this one 😄

**Comment by kentcdodds** [comment]
I set this as medium priority meaning that I'd _love_ to release the site with this as our on boarding experience, but it's not a _must_. I think that it would _really_ catch people's attention to have something like this though.

**Comment by bernard-lin** [comment]
Sounds good to me!

**Comment by kentcdodds** [comment]
Alrighty, I've got something started! Here's what anyone needs to know to make it more awesome:

- The markdown file that's rendered on the right side is [here](https://github.com/kentcdodds/glamorous-website/blob/master/pages/getting-started/content/guide.md), the code snippet on the left is [here](https://github.com/kentcdodds/glamorous-website/blob/master/pages/getting-started/content/getting-started-code.raw.js)
- I took a lot of inspiration from @tkh44 [here](https://github.com/tkh44/emotion/commit/c3faf205543a7c856f40d0f7e42b2faec17577b2), [here](https://twitter.com/tkh44/status/875768337061617664) and [here](https://twitter.com/tkh44/status/878849764992876544)
- Unfortunately, next doesn't recognize changes to markdown or the `.raw` files. So you can save and refresh and nothing happens. To get around this I just add a comment to the file that's importing those (which it _does_ watch for changes) and change that file to get things to reload.

Help is definitely appreciated!

**Comment by tkh44** [comment]
@kentcdodds you need to emit the files I believe.

https://github.com/zeit/next.js/blob/master/examples/with-global-stylesheet/next.config.js#L6

**Comment by tkh44** [comment]
I wouldn't have the user style the code block. Just leave that one out so that it is more accessible to read the intro snippets. This is just something I observed.

Also you should be able to hook up analytics events to the examples to see where people get stuck.

**Comment by kentcdodds** [comment]
> you need to emit the files I believe.

@tkh44, not sure what you mean... It works [as-is](https://rc.glamorous.rocks/getting-started/) 🤔 

Great observations/perspective/learnings. Thank you!

**Comment by tkh44** [comment]
@kentcdodds I was referring to the hot reloading not working. I totally spaced out while writing it I guess. 😅

**Comment by tkh44** [comment]
btw it looks great!

**Comment by kentcdodds** [comment]
Hey @tkh44, I was looking into `emit-file-loader` and it looks like it's internal to next... Is it available to me? Also, do you have any idea how I'd actually use it/what exactly it does?

**Comment by bernard-lin** [comment]
Oops sorry, totally dropped the ball on this one! Let me know if you need anything else

**Comment by kentcdodds** [comment]
Yes please! Any help you can give would be appreciated :) It's pretty much in the same state it was when you left it :)
