### ISSUE TITLE
Add a "practices to avoid" section

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#159]
Just didn't want to forget this. But it would be great to have a section of the docs dedicated on what not to do with glamorous.

**Comment by paulmolluzzo** [comment]
One thing I really like about `glamorous` is that it's not too opinionated about how it's used. I'm not quite sure what consitutes "bad" practices. Did you have something specific in mind? I don't want to tell someone that they're "wrong" just for writing the code in a way that I might not prefer.

I think the only really Wrong Way is to shove all your CSS on one parent element and then use plain old CSS child selectors the rest of the way. Something like:

```js
const GlobalWrapper = glamorous.div({
    '& .child .grand-child .great-grand-child ul li a span::after': {
        color: 'blue'
    }
})
<GlobalWrapper>
    // code
</GlobalWrapper>
```

That's like a bad practice for... _life_. 😅 

Still, even child selectors are totally fine in some circumstances.

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see [the glamorous README](https://github.com/paypal/glamorous) for more information.
