### ISSUE TITLE
Make or find a babel plugin to load markdown as a string

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#160]
Because I don't like the current implementation of our content. I would prefer it to just be markdown. If anyone's up for exploring this, be my guest. I'm not 100% sure I know what I want here, but I think a babel plugin would be the way to go.

**Comment by kentcdodds** [comment]
By this I mean I want to be able to do `const foo =
require ('./content/foo.md')` and it will transpile that to: `const foo = 'the markdown content'`

This will need to be localized with our fallback rules, meaning we'll need to run the build once for each locale with an environment variable or something. But I think it'll be better, and it's something we need to do to make a static version of the site anyway so that's fine with me.

**Comment by liadbiz** [comment]
I googled that and find a plugin herea https://github.com/khrome83/babel-plugin-transform-md-import-to-string. but I am not sure it will work.

I will try it tomorrow~

**Comment by liadbiz** [comment]
@kentcdodds I build a plugin that can transpile markdown require into string. https://github.com/liadbiz/babel-plugin-transform-md-require-to-string 
hope it would help!

**Comment by kentcdodds** [comment]
Thanks @liadbiz! I put some work into this in #177 :)

**Comment by kentcdodds** [comment]
This has been implemented and it's pretty sweet! Docs have been updated and people can finally start using real markdown now :tada:
