### ISSUE TITLE
Feedback on website

### ISSUE THREAD

**Issue by tdeschryver** [kentcdodds/glamorous-website#163]
I just went through the website and wanted to share my thoughts.

- First things first, it looks awesome! Kudos to everyone!
- Seems like the [api](https://rc.glamorous.rocks/api) page has another style on it
  - other pages are split up between sections, this page isn't
  - the config part a bit looks strange to me (bullet list + checkbox)
- Would it be helpful to create a section tag to link a section on a page. For example: https://rc.glamorous.rocks/advanced#theming
- Create a page for peoples using glamorous, tweeting about glamorous? Or maybe put it with the community examples?

Thoughts?

**Comment by paulmolluzzo** [comment]
> Seems like the api page has another style on it other pages are split up between sections, this page isn't

I think this is just a lack of content. It's already taking some more shape and if you inspect you can see the `section` tags.

> the config part a bit looks strange to me (bullet list + checkbox)

Agreed. I think some additional (global?) styling on `ul`s would be beneficial here. Even if they just get some `padding`/`margin` to fall in line with the rest of the content.

> Would it be helpful to create a section tag to link a section on a page. For example: https://rc.glamorous.rocks/advanced#theming

Absolutely! Would love to have this!

> Create a page for peoples using glamorous, tweeting about glamorous? Or maybe put it with the community examples?

Another great idea! There's already [`USERS.md`](https://github.com/paypal/glamorous/blob/master/other/USERS.md) in the `glamorous` repo, so that's a great start for content.

**Comment by tdeschryver** [comment]
I see you already made a PR for the header links.
Is there something that I can take on my plate? :)

**Comment by paulmolluzzo** [comment]
Oh, sorry about that!

The list styling needs some love, if you want to take that on. And also address that one checkbox you mentioned. I agree it's weird looking. 😀

I'm not sure where to put the list of people using `glamorous` so if you want to experiment in a PR that'd be cool too. Originally we had a list of logos on the home page (see #8), but I'm not sure that'll work with the list we have now. 🤔

Of course, you can address another issue if you like. #102 would be a nice one to get done.

And finally you can review the PR that I opened. If you think it's good we can merge it in. 😀

**Comment by tdeschryver** [comment]
Oh no problem! I was just asking so we're not picking up the same issue 😄 

I'll try to send a PR about the list styling later today + your PR.
And later this week I'll check out #102 or the peoples pages if its still available!

**Comment by tdeschryver** [comment]
I had some time today and started on the users page, but I'm not sure.... So far this is what I came up with.

![image](https://user-images.githubusercontent.com/28659384/27444141-afc30838-5775-11e7-8e02-b09aa1c46899.png)
