### ISSUE TITLE
Help implement something

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#179]
We're going to be running builds for every locale and I want to run them in parallel. But eventually there will be too many to run in parallel and we should throttle how many we have.

We're going to use concurrently to run things in parallel and this could be simplified if we implement this: https://github.com/kimmobrunfeldt/concurrently/issues/96

Anyone wanna work on that? Should be kinda fun :) Especially if you've been wanting to learn RxJS :)

**Comment by piq9117** [comment]
I've been using RxJS in angular not sure if my skills will suffice. 🤔

**Comment by shakyShane** [comment]
here's a hint, there's more to it than this, but it should provide enough pointers.

the following will only ever run a maximum of 2 processes at any one time.

```js
const Rx = require('rxjs');
const {exec} = require('child_process');

function getProcesses(processes) {
    return processes.map(command => {
        return Rx.Observable.create(observer => {
            exec(command, (error, stdout, stderr) => {
                if (error) {
                    observer.error(error);
                    return;
                }
                console.log(`stdout: ${stdout}`);
                console.log(`stderr: ${stderr}`);
                observer.complete();
            });
        });
    });
}

const processes = getProcesses(["cm1", "cm2", "cm3"])
    .mergeAll(2)
    .subscribe(x => {
        console.log('maximum concurrency of 2')
    });
```

**Comment by gillchristian** [comment]
@shakyShane awesome :sunglasses: 

I might have time this Sunday to work on this but can't promise so feel free take it :smile:

**Comment by abs-zero** [comment]
How do I get started? 😀

**Comment by kentcdodds** [comment]
I recommend going to the issue: https://github.com/kimmobrunfeldt/concurrently/issues/96

And mention you want to help out. Then follow the contributing guidelines. [this could help](http://kcd.im/pull-request) especially if you're new to OSS :)

Good luck! And thank you!

**Comment by trxcllnt** [comment]
side note: I love and recommend paul betts'a [spawn-rx](https://github.com/paulcbetts/spawn-rx) for doing child procs with Rx in node

**Comment by kentcdodds** [comment]
For now, I think we can just do fancy stuff in the `package-scripts.js`, but would really love it if someone were to implement this so we don't have to do that.

**Comment by kentcdodds** [comment]
Ok, so I switched from parallel to series on the build script and that'll fix the build breaking, but I'd love to get this implemented so we could get things running in parallel again. Our build runs pretty slow now...

**Comment by ndelangen** [comment]
Have you considered using CircleCI workflows to build in parallel?

**Comment by kentcdodds** [comment]
I suppose we could try that. I've used CircleCI before... Maybe I should try it again...
