### ISSUE TITLE
title not being shown?

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#180]
This is weird... https://rc.glamorous.rocks/

<img width="631" alt="screen shot 2017-06-30 at 12 57 24 pm" src="https://user-images.githubusercontent.com/1500684/27750125-b165c5e4-5d93-11e7-97fa-c286c0cfcc89.png">

Anyone know what's going on?

**Comment by paulmolluzzo** [comment]
When I inspect it's not in the `title` tag.
![screen shot 2017-06-30 at 3 16 34 pm](https://user-images.githubusercontent.com/737065/27750707-fde5e198-5da6-11e7-9b15-9868a2219959.png)

**Comment by tdeschryver** [comment]
Seems like the title does show for a couple of seconds while the page is still loading...
Could it be that it has something to do with [NextScript](https://github.com/kentcdodds/glamorous-website/blob/master/pages/_document/index.js#L40)? After removing this line, the title shows locally.

**Comment by kentcdodds** [comment]
Hmmmmm 🤔

**Comment by paulmolluzzo** [comment]
We can't remove `NextScript`, that's the bundle.

It's possible that it's because we're using `Head` in the `_document` and in the page and not setting the `title` in the page, or that `title` doesn't have content in all the pages, or something along those lines.

**Comment by kentcdodds** [comment]
> We can't remove `NextScript`, that's the bundle.

lol, I read this as:

> We **can** remove `NextScript`, that's the bundle.

😅 

And now the site's not interactive 😅 

I'll be eh... reverting that now :)

**Comment by paulmolluzzo** [comment]
😂

So, the `Head` in the pages not having a title might be to blame. It seems annoying to repeat it everywhere, but everything we want in the `<head>` needs to be defined in the `Head` component on every page. We probably even have to move the `viewport` stuff into each instance.

**Comment by paulmolluzzo** [comment]
Should be closed by #190. Please make a new issue if it persists on a specific page.
