### ISSUE TITLE
Improve a11y of the locale chooser

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#184]
**Problem Description:**

If you're just using the keyboard, the locale chooser isn't very accessible. We can do better :)

![a11y](https://user-images.githubusercontent.com/1500684/27756331-d0eb6854-5db3-11e7-89d1-69bec5b43183.gif)

**Suggested Solution:**

Let's make the keyboard only experience great:
- Highlight the dropdown
- Use proper `aria` tags
- Improve the highlight of individual items

One other thing I noticed is that if you click on it, then click away, it doesn't go away and I would expect it to.

cc @tdeschryver

**Comment by tdeschryver** [comment]
Closed by #185
