### ISSUE TITLE
Improve mobile

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#189]
**Problem Description:**

The title is too small and the nav should probably have a background color (could have an light transparency)

<img width="335" alt="screen shot 2017-07-02 at 10 48 13 am" src="https://user-images.githubusercontent.com/1500684/27771840-1653d974-5f14-11e7-9ea2-fab9a02a4ce8.png">
<img width="336" alt="screen shot 2017-07-02 at 10 48 05 am" src="https://user-images.githubusercontent.com/1500684/27771839-1651b086-5f14-11e7-8bed-ad2558a8ad62.png">

**Suggested Solution:**

Not sure, but open to PRs :)

**Comment by paulmolluzzo** [comment]
I thought I fixed this in #188... 😕

We had the `h1` as `3vw` for mobile. It should be more like `5vw`. IMHO `rem` is better for fonts in general.

**Comment by kentcdodds** [comment]
Yeah, I thought I was being clever with the vw thing, but it's dumb and we should remove it in favor of rem or em.

**Comment by paulmolluzzo** [comment]
😂

[`rem`](https://zellwk.com/blog/rem-vs-em/)

**Comment by paulmolluzzo** [comment]
For whoever takes this on, IIRC our base styles are using `rem`, so it sorta weighs a little more favorably to using it everywhere. I'd also suggest/ask that any other font size specification be changed to match the unit being used. Just makes everything easier to reason about.
