### ISSUE TITLE
Improve a11y of docs pages

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#191]
This text isn't very accessible 😶 the font is too thin/small/low contrast? Ideas?

![screenshot_20170702-152528](https://user-images.githubusercontent.com/1500684/27773613-ce400d84-5f3a-11e7-9ba5-378c5da1acb4.png)

![screenshot_20170702-152532](https://user-images.githubusercontent.com/1500684/27773614-d65befba-5f3a-11e7-8162-7a06d0c70673.png)

**Comment by paulmolluzzo** [comment]
The obvious things are to increase the font weight and size, and maybe force the bulk of the content to have a white BG. But there may be more to it than that. @mwickett any thoughts? I feel like we've addressed this before but maybe we regressed?

**Comment by mwickett** [comment]
That's odd. It wasn't like that before I don't think.

Sorry, I haven't been keeping up lately. Can take a look tomorrow
afternoon.

**Comment by mwickett** [comment]
Definitely a regression. This is what I see on my out-of-date local copy.

<img width="411" alt="screenshot 2017-07-03 19 38 19" src="https://user-images.githubusercontent.com/845983/27810380-84c579f8-6027-11e7-9540-32b51c3d3e9a.png">

**Comment by paulmolluzzo** [comment]
@mwickett can you blame/diff the related files and submit a PR to fix this please? This was valuable work you put in, we don't want to lose it. 😀

**Comment by mwickett** [comment]
The only file that changed in my PR #170 was `styles/base.js` and it doesn't look like anything has changed since then.

This is unrelated, but I can't run `master` locally - getting this error:

```
error  in ./pages?entry

Syntax Error: /Users/michaelwickett/Sites/oss/glamorous-rocks/other/babel-plugin-l10n-loader.js:46
        )
        ^
SyntaxError: Unexpected token )


 @ multi ./pages?entry
```

**Comment by kentcdodds** [comment]
You'll need to upgrade to node 8, sorry!

**Comment by paulmolluzzo** [comment]
I wonder if it's the `opacity` or that we're re-setting the `fontFamily` on the `Wrapper` component: https://github.com/kentcdodds/glamorous-website/commit/663e539910042f8e07fa9a17d0d9c7d3d7f4215d#diff-bc4150d023d3255136db671d61ac93f2

**Comment by paulmolluzzo** [comment]
Is this still an issue?

**Comment by kentcdodds** [comment]
Ummm... I guess we're good :+1:

**Comment by mwickett** [comment]
I think it's good - the code editor stuff still flags on aXe, but that's a bit of a ball of wax that may be a challenge to dig into.

I dropped the ball on this one guys, my apologies!

**Comment by kentcdodds** [comment]
Thanks for all you've done @mwickett
