### ISSUE TITLE
Translate the site into German

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#194]
I would like to have this site translated into German. Who wants to help?

**Comment by kentcdodds** [comment]
I'm going to start now :)

**Comment by kentcdodds** [comment]
So I kinda sorta started on this, but I don't know German! Who wants to [help](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md)?

**Comment by liadbiz** [comment]
@kentcdodds how about Chinise version? I have filed an issue here #202 :smile:

**Comment by kentcdodds** [comment]
Still want to get the site translated into German, but we no longer need to have this issue open.

**Comment by pzi** [comment]
Happy to help out with German, want me to create a new issue similar to the [french one](239) @kentcdodds? :)

**Comment by kentcdodds** [comment]
Hi @pzi! Feel free to just start opening pull requests. We do already have german added to the site, but there are some sections which are out of date or not yet translated :)

Note: every PR will need to be reviewed by a native speaker to be merged. Thanks!

**Comment by pzi** [comment]
No worries, will do! I noticed the existing German translations and will keep the terminology used consistent as much as possible.

I've seen the 'native speaker review' requirement and will hopefully find someone to do so when I put up a PR :)
