### ISSUE TITLE
Markdown list rendering funky

### ISSUE THREAD

**Issue by tdeschryver** [kentcdodds/glamorous-website#196]
**Problem Description:**
There is an extra `<` while rendering a markdown list (ordered and unordered).

Can be seen in [Advanced Guides](https://rc.glamorous.rocks/advanced/)

![image](https://user-images.githubusercontent.com/28659384/27840154-11af4b12-60f7-11e7-8b20-f59b719c4647.png)

**Suggested Solution:**
Removing the last line (` .slice(3, -5)`) in `md-to-html` seems to fix this problem but I don't know the impact of it. Ran tests and opened the website and it seems OK.
```
import remarkHtml from 'remark-html'
import stripIndent from './strip-indent'

export default mdToHTML

function mdToHTML(md: string | null): string {
  if (!md) {
    return ''
  }
  return remark()
    .use(remarkHtml)
    .processSync(stripIndent(md))
    .toString()
    // .slice(3, -5)
}
```

**Comment by paulmolluzzo** [comment]
Hmm, probably need to update that to be `slice(3, -6)`.

We're slicing off some extra HTML tags of the rendered HTML. You can see it by inspecting the source, and it's probably happening because these are `li`s and not `p`s.

I wonder if simply putting an empty line after the list in the markdown would solve it.

**Comment by tdeschryver** [comment]
@paulmolluzzo just tried adding an empty line but the `<` is still being rendered.

**Comment by kentcdodds** [comment]
I've got some ideas for this. Let me give it a look

**Comment by paulmolluzzo** [comment]
I'm thinking using `replace` to remove the first and last tag.

**Comment by kentcdodds** [comment]
I'm pushing a PR now.
