### ISSUE TITLE
translate website into Chinise 

### ISSUE THREAD

**Issue by liadbiz** [kentcdodds/glamorous-website#202]
Thanks @kentcdodds , now we can handle docs with markdown files, it  will be so easy to translate docs. I would like to translate thie website into Chinise. If anyone can help, raise you hands here so that we can work together :smile_cat:

**Comment by kentcdodds** [comment]
Wonderful! Yes! Please get started! I recorded myself adding German. Wasn't practiced so I had to do a lot of stuff, but it will hopefully be helpful: http://www.twitch.tv/kentcdodds/v/156447077?sr=a&t=17s

**Comment by bernard-lin** [comment]
Happy to help!

**Comment by kentcdodds** [comment]
Ok, I've added chinese. All you need to do now is follow [the contributing guidelines](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md). Good first step would probably be to fix anything Google Translate messed up [here](https://github.com/kentcdodds/glamorous-website/blob/master/pages/index/content/zh/index.md) :smile:

**Comment by bernard-lin** [comment]
Good reference for terminology here: https://discountry.github.io/react/ This will probably form the core of the Chinese translation when React gets its translation tool up and running
Referenced in https://github.com/facebook/react/issues/9860

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see [the glamorous README](https://github.com/paypal/glamorous) for more information.
