### ISSUE TITLE
Write a blog post

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#205]
For the RELEASE!!! HYPE!!!

Also, wanna release a new breaking change for glamorous. There are one or two things I'd like to do for that... People love new major versions #hype

**Comment by paulmolluzzo** [comment]
🎉🎉 Get Hyped!

Post a link to the draft when we're ready for it. I'd love to give it a look.

**Comment by paulmolluzzo** [comment]
Might want to get started on this... 😄

**Comment by kentcdodds** [comment]
Haha, yeah 😅 
hopefully this weekend. Been working on getting the releases ready. I think the codemod is ready. Could you review that? https://github.com/paypal/glamorous/pull

**Comment by kentcdodds** [comment]
Tracking this here: https://github.com/paypal/glamorous/pull/253

**Comment by paulmolluzzo** [comment]
![](https://media.tenor.co/images/c8adaa18494424aceea3b6a2104e8016/raw)
