### ISSUE TITLE
Twitter card

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#21]
Before we officially announce the website, we should probably have a slick looking twitter preview card for it so when folks tweet about it, they see something awesome (in addition to the equally awesome domain: https://glamorous.rocks/)

So I'd love to get some mocks together for a good twitter card. We could do small:

<img width="607" alt="screen shot 2017-05-30 at 11 59 45 am" src="https://cloud.githubusercontent.com/assets/1500684/26597516/81c13bec-452f-11e7-9c06-f8cfa6bccf0f.png">

Or large:

<img width="607" alt="screen shot 2017-05-30 at 12 00 18 pm" src="https://cloud.githubusercontent.com/assets/1500684/26597536/90778ad8-452f-11e7-8f8a-035de2b9091d.png">

Once we have the image we want to use, we'll need to implement the twitter/facebook meta tags. I did this with JavaScript Air and this is what it looked like:

```html
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="google-site-verification" content="85n8ZBk_3hSeShlRmsVJXgDolakFG4UsMJgpy3mQyPs" />
<meta name="theme-color" content="#efdd4f" />
<meta name="author" content="JavaScript Air" />
<link rel="publisher" href="https://plus.google.com/b/105493143005968326308" />
<meta name="description" content="Episode 049 of the live JavaScript broadcast podcast. Kent C. Dodds has sunset JavaScript Air. No shows are currently scheduled." />
<meta name="description" content="Episode 049 of the live JavaScript broadcast podcast. Kent C. Dodds has sunset JavaScript Air. No shows are currently scheduled." />
<meta name="keywords" content="Maybe one day..." />
<meta name="author" content="JavaScript Air" />
<meta name="copyright" content="2016" />
<meta name="application-name" content="JavaScript Air Podcast" />
<meta property="og:title" content="Maybe one day..." />
<meta property="og:type" content="video" />
<meta property="og:image" content="https://javascriptair.com/episodes/2222-10-18/screenshot.png" />
<meta property="og:url" content="https://javascriptair.com/episodes/2222-10-18" />
<meta property="og:description" content="Episode 049 of the live JavaScript broadcast podcast. Kent C. Dodds has sunset JavaScript Air. No shows are currently scheduled." />
<meta property="og:site_name" content="JavaScript Air" />
<meta property="video:release_date" content="2222-10-18" />
<meta property="og:video:url" content="https://www.youtube.com/embed/" />
<meta property="og:video:secure_url" content="https://www.youtube.com/embed/" />
<meta property="og:video:type" content="text/html" />
<meta property="og:video:width" content="1280" />
<meta property="og:video:height" content="720" />
<meta property="og:video:url" content="https://www.youtube.com/v/?version=3&amp;amp;autohide=1" />
<meta property="og:video:secure_url" content="https://www.youtube.com/v/?version=3&amp;amp;autohide=1" />
<meta property="og:video:type" content="application/x-shockwave-flash" />
<meta property="og:video:width" content="1280" />
<meta property="og:video:height" content="720" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="Maybe one day..." />
<meta name="twitter:description" content="Episode 049 of the live JavaScript broadcast podcast. Kent C. Dodds has sunset JavaScript Air. No shows are currently scheduled." />
<meta name="twitter:image" content="https://javascriptair.com/episodes/2222-10-18/screenshot.png" />
<meta name="twitter:image:alt" content="JavaScript Air episode card with information about the guests, the episode description, and the episode date and time" />
<meta name="twitter:site" content="@JavaScriptAir" />
<meta name="twitter:creator" content="@JavaScriptAir" />
<meta name="twitter:player" content="https://www.youtube.com/embed/" />
<meta name="twitter:player:width" content="1280" />
<meta name="twitter:player:height" content="720" />
<link rel="shortcut icon" type="image/png" href="/favicon.ico" />
<link rel="manifest" href="/resources/manifest/manifest.json" />
```

Some of those things are not relevant, but much of it would be :)

**Comment by paulmolluzzo** [comment]
Let's do a large one.

@jonmajorc can you pull an image from the design? I love the way you did the logo and name with the large, faint `g` background in the homepage.

**Comment by iamrudra** [comment]
Happy to look into this if someone else isn't.

**Comment by kentcdodds** [comment]
Go for it! 👍

**Comment by iamrudra** [comment]
This is the image we want for the card, right? Confirming as @paulmolluzzo has mentioned something about a faint `g` which I do not see on the current website. 

![image](https://cloud.githubusercontent.com/assets/12117759/26602550/b52cdf3c-4538-11e7-9d7c-d5bab7594bdf.png)

**Comment by kentcdodds** [comment]
See the current wireframe: #8

**Comment by kentcdodds** [comment]
So I think that we're going to want [`summary-large-image`](https://dev.twitter.com/cards/types/summary-large-image). Here's a [markup reference](https://dev.twitter.com/cards/markup).

**Comment by kentcdodds** [comment]
You'll probably make your changes to https://github.com/kentcdodds/glamorous-website/blob/master/pages/_document.js

I'd recommend making special component that's responsible for just these `meta` tags and using that component in `_document.js`

**Comment by iamrudra** [comment]
Here's the compressed image - 

![glamorous_logo](https://cloud.githubusercontent.com/assets/12117759/26606249/13df3414-4546-11e7-9ce4-e5107f181699.png)

**Comment by kentcdodds** [comment]
I wonder if we should add some descriptive text to it. If I saw that in my feed, I probably wouldn't be as interested. But if it said: "Maintainable CSS with React" in below "glamorous" then I'd be more inclined to look into it.

Also, does the text look off-center to anyone else?

**Comment by paulmolluzzo** [comment]
Yes this does go in the `_document.js`, and I agree with @kentcdodds about a separate component.

If we want to have a _different_ card for each page we can do this with the `Head` component provided by `next`, but I don't know that we need that.

**Comment by kentcdodds** [comment]
Yeah, we can do more dynamic stuff later.

**Comment by paulmolluzzo** [comment]
> Also, does the text look off-center to anyone else?

The text is _barely_ too far left (21px by my measurement), but the lipstick adds weight to the left which is what's throwing you off. Maybe we want to treat the lipstick and the text as a single lockup and center that, which would mean moving the lockup to the right about `100px`.

Also, there's a white triangular artifact  ~165px below the lipstick icon.

**Comment by kentcdodds** [comment]
Ah, yeah, good catch. @jonmajorc could you get us a sweet new image based on the specifications [here](https://dev.twitter.com/cards/types/summary-large-image)?

**Comment by iamrudra** [comment]
It'd be nice to have access to the sketch/design files, if possible. So that things can be iterated upon by folks when needed.

**Comment by jonmajorc** [comment]
@kentcdodds let me look into the specifications and see what I can do!

**Comment by jonmajorc** [comment]
Twitter Card size is 600 x 330. Also that blemish @paulmolluzzo found is fixed too! Good eye!! 👀 👍  
![twitter card](https://cloud.githubusercontent.com/assets/7799266/26609868/93946738-4569-11e7-9207-9ba84a80fe95.png)

**Comment by iamrudra** [comment]
@jonmajorc - Am I missing something here? The [twitter doc](https://dev.twitter.com/cards/types/summary-large-image) for summary card with large image says -

> Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels.

**Comment by jonmajorc** [comment]
@iamrudra their example was 600 x 330, so I decided to run with that size first and then if anything we can scale it up if need be 😄, but we could go big or go home!

**Comment by kentcdodds** [comment]
Could we do the maximum size they mention? Better resolution and stuff 😀

**Comment by iamrudra** [comment]
Also, we will need the following details for the card:

- site: `Twitter Handle for Glamorous`
- creator: `Usually the author of the article but we can keep it same as glamorous`
- title: `Glamorous: Maintainable CSS with React` (Working title)
- Description: `TBD`
- Image: `URL of image`
- URL: `Website` (https://glamorous.rocks)

**Comment by paulmolluzzo** [comment]
Let's start at the max as @kentcdodds suggested. The image can be loaded from `/static/` like all other assets.

For whoever does this, once the PR is open the CI we have for staging should provide a public URL we can pass through Twitters validator.

@jonmajorc design assets can go in some directory I guess? Or maybe we want a separate repo just for artifacts? Ideally we'll get all the design components (logos, colors, fonts, etc) into an obvious and useful place in the repo and not need formal static designs forever. 🤷‍♂️

**Comment by jonmajorc** [comment]
Going big am not going home! (compressed too with tinypng.com. Thanks @iamrudra!)
![twittercard](https://cloud.githubusercontent.com/assets/7799266/26611099/74c2a45c-4571-11e7-8290-dbdc822339be.png)

**Comment by jonmajorc** [comment]
If you are looking for the design resources: https://www.figma.com/file/KUro18mAUhgFixMt61hTn0ja/Glamorous

**Comment by kentcdodds** [comment]
Love it!

**Comment by iamrudra** [comment]
Preview of the card! :)

![image](https://cloud.githubusercontent.com/assets/12117759/26644134/9b3c2f78-45e8-11e7-9600-bb08b40efb5b.png)

**Comment by kentcdodds** [comment]
OH SNAP! That's soooo awesome! 😍 

Check this out: https://twitter.com/glamorousCSS :)

**Comment by iamrudra** [comment]
Nice. We have a handle. Can we finalize the details of the content so we can wrap this one up?

**Comment by kentcdodds** [comment]
I've slightly modified what @jonmajorc had:

```
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@glamorousCSS">
<meta name="twitter:creator" content="@glamorousCSS">
<meta name="twitter:title" content="Maintainable CSS with React">
<meta name="twitter:description" content="React component styling solved with an elegant API, small footprint, and great performance">
<meta name="twitter:image" content="IMAGE_URL">
```

**Comment by kentcdodds** [comment]
Cool! So this has been merged #30 so we're good. Though I just realized something. We should probably only make that show up for the homepage. It really is only necessary for when folks are tweeting something like: "Hey check out glamorous.rocks!" Boom! Big image that's awesome. But it would be really annoying if someone tweeted: "The answer to your question is in the docs: glamorous.rocks/docs/thing" Boom! Big image that's awesome, but also a little out of context.

So I think it'd be better to have the smaller version for all other pages:

<img width="607" alt="81c13bec-452f-11e7-9c06-f8cfa6bccf0f" src="https://cloud.githubusercontent.com/assets/1500684/26656195/58fa2204-461b-11e7-8a8c-61e6dd860cd0.png">

Perhaps that took the title and the first sentence or so of the docs 🤔 we're still working on something there... The content can be updated later. For the first iteration though, it'd be good to have the logic to only use the big image on the homepage.

**Comment by iamrudra** [comment]
>But it would be really annoying if someone tweeted: "The answer to your question is in the docs: glamorous.rocks/docs/thing" Boom! Big image that's awesome, but also a little out of context.

Agree. Can you point me where to look at for make it home page specific only?

**Comment by kentcdodds** [comment]
I'm not sure, but I expect that `_document.js` (where you made the original changes) has some props that can tell you what page is being loaded or something 🤔 I'm still new to next.js :)

**Comment by paulmolluzzo** [comment]
You can populate the `head` like this: https://github.com/zeit/next.js/blob/v3-beta/readme.md#populating-head

**Comment by kentcdodds** [comment]
Oh, that's pretty cool! So we should probably move the existing `meta` tags to the `index.js` file using that method :+1:

**Comment by paulmolluzzo** [comment]
Does anyone have an interest in taking this on? @iamrudra? If anyone is interested and just needs a little direction, post here and we'll be happy to help!

**Comment by iamrudra** [comment]
@paulmolluzzo - React not my strong suit but I will get back on this in next couple of days (can I or can't I do this). Does that work?

**Comment by kentcdodds** [comment]
That's fine. In the mean time will open this up for anyone else to do if they like.

**Comment by iamrudra** [comment]
@kentcdodds - It says it was added to `Ready` - Does that mean it has already been worked upon by you?

**Comment by kentcdodds** [comment]
Just means that what we want to do has been defined and it's ready for anyone to work on it.

**Comment by iamrudra** [comment]
I looked at `pages/index/index.js` and checked out the reference doc link that @paulmolluzzo shared. Unfortunately didn't get much idea where exactly should I make changes. :(

PS - My now build fails with code `137` - Is anyone else facing the same thing?

**Comment by kentcdodds** [comment]
Huh, weird about your build. No idea what's causing that 🤔

As for where to make changes, I'm afraid that I don't have time right now to direct you further, sorry.

**Comment by iamrudra** [comment]
Yeah, no worries. I just wanted to provide a status update (as promised in my previous comment) so that it's clear to other contributors that this one is up for grabs! :)

**Comment by emmafallancy** [comment]
> If anyone is interested and just needs a little direction, post here and we'll be happy to help!

@paulmolluzzo @kentcdodds Has it already being resolved? If not, I would be happy to give it a go for this. Just wondering if it would be fine to have the twitter meta tag to be in a component and be used across other pages that would need it and populate it with `link/head`.

**Comment by iamrudra** [comment]
@emmafallancy - AFAIK, I was the only one touching this and I am not anymore. So by all means, do the honors! :)

**Comment by emmafallancy** [comment]
@iamrudra Cool 😄 I will pick it up then 👍 Thanks!

**Comment by emmafallancy** [comment]
I just realised that the image for the twitter card for smaller version looks a bit off than the current existing ones that we have using large twitter card. Was wondering if there is any suggestion on having to resize the image, or having its own image for all other pages?

This is how it looks like for _Glamorous homepage_ 
<img width="506" alt="Homepage - Glamorous Twitter Card" src="https://user-images.githubusercontent.com/22838512/27515798-8ce310b6-59ef-11e7-9c57-fc384578e4da.png">

And this is how it looks like for other pages in smaller version
<img width="506" alt="Basics - Glamorous Twitter Card" src="https://user-images.githubusercontent.com/22838512/27515819-167aceea-59f0-11e7-935a-9af2a4fa456b.png">

**Comment by kentcdodds** [comment]
Yeah, we'll want to use a different image for the smaller card. Perhaps @jonmajorc can help make one? Also, the colors have changed slightly since the original card was made, perhaps we should update the large card image as well...

**Comment by emmafallancy** [comment]
Cool! I guess for now, what I can do is to use the current existing image file for the card that we have in `/static/images` directory (apart from updating the PR based on @paulmolluzzo recommendation) and once confirmed on the update for the large card image and the new image for smaller card, I will update again the PR that I have in #176 

Would that be fine @kentcdodds, @paulmolluzzo ?

**Comment by kentcdodds** [comment]
Sounds good to me

**Comment by jonmajorc** [comment]
Here it is again! I optimized them with Tinypng.com and I changed the font color and weight based on website. Let me know if the smaller version works @emmafallancy and @kentcdodds, or if there is any other additional work you need from me 😄 
![glamorous_large_card](https://user-images.githubusercontent.com/7799266/27516798-84251280-5986-11e7-9d26-6b4e05ff810c.png)
I could not find anything in the API docs for image size of smaller cards so I cut the size in half... Send me a link to the Twitter card API for smaller cards so I can get an optimized image for you @emmafallancy 
![glamorous_small_card](https://user-images.githubusercontent.com/7799266/27516799-8427f522-5986-11e7-993c-a12ae62b5f0a.png)

**Comment by emmafallancy** [comment]
Hi @jonmajorc 👋 , 

here's how it looks like for the smaller version of the card. Would require some resizing/optimisation for the smaller version?
<img width="508" alt="Smaller version twitter card" src="https://user-images.githubusercontent.com/22838512/27517252-d08b03b0-5a0c-11e7-8b08-47707d1a0b5f.png">

The bigger version looks fine to me 😄 
<img width="508" alt="Bigger version twitter card" src="https://user-images.githubusercontent.com/22838512/27517265-fa5342c0-5a0c-11e7-9c06-1f0a55436995.png">

**Comment by kentcdodds** [comment]
Looks like the aspect ratio is 1:1 for the smaller one. Not sure about their recommended resolution, but if we could just get a square version of the image, that'd probably be great 👍

**Comment by paulmolluzzo** [comment]
> twitter:image

A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 1:1 with minimum dimensions of 144x144 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. The image will be cropped to a square on all platforms. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

https://dev.twitter.com/cards/types/summary

**Comment by kentcdodds** [comment]
Awesome, thanks! Let's do the biggest size available and optimize it with https://tinypng.com

**Comment by jonmajorc** [comment]
Oops! I exported the wrong slice in Figma 😄. This should hopefully do it! This would be able to be used for both large and small Twitter cards. The aspect ratio is now 1:1 at the largest size of 4096x4096!
![glamorous_card](https://user-images.githubusercontent.com/7799266/27518697-55e936ba-59ab-11e7-88b7-16285dea5da7.png)

**Comment by emmafallancy** [comment]
Here's how it looks like for now,

_*Large version twitter card*_
<img width="508" alt="Large summary twitter card" src="https://user-images.githubusercontent.com/22838512/27520491-242c8ec4-5a50-11e7-9a02-2c597a2d2433.png">

_*Small version twitter card*_
<img width="507" alt="Small summary twitter card" src="https://user-images.githubusercontent.com/22838512/27520496-3da10a24-5a50-11e7-914d-8c34348f6f32.png">

Looks fine for me with the new image on small `summary` twitter card. Thanks @jonmajorc ! 😄 

@kentcdodds @paulmolluzzo @jonmajorc - Any thoughts with large and small twitter card appearance?

**Comment by kentcdodds** [comment]
I think this is done...
