### ISSUE TITLE
Add metadata to translated files indicating whether they're up to date

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#218]
**Problem Description:**

Some translated files are out of date. This could cause people to view them and think that's all there is when in reality there's more updated information.

**Suggested Solution:**

Let's add metadata to the content object [here](https://github.com/kentcdodds/glamorous-website/blob/83c98ee6d0f9c81230b83905f3a6dcef9f967ba1/other/babel-plugin-l10n-loader.js#L82-L89) indicating whether the translation is updated so we can use that info in the UI.

Could probably use some of the logic we use [here](https://github.com/kentcdodds/glamorous-website/blob/83c98ee6d0f9c81230b83905f3a6dcef9f967ba1/other/list-l10n.js#L23-L38)

I'm gonna say that this is a must for release. I don't want to release locales with outdated translations and I think we can probably get this done faster than we can get the translations done.

**Comment by paulmolluzzo** [comment]
Do you have an idea for determining if a file is outdated? For example, writing a date into the metadata and comparing it to... something? I don't think we can compare "last updated" dates across languages. We would need to say that one is the source of truth, and account for small changes like typos that may not affect translations.

I'm wondering if it's better to just put the date the source .md file was last updated in the rendered content. It would put the onus on the reader to determine if it's accurate or not. If we use a relative date (e.g. "Last updated 1 month ago") that might make it easier at a glance.

**Comment by tdeschryver** [comment]
I was thinking the same thing as @paulmolluzzo.
But where I still see an issue is; what if the content isn't being changed, then after a month it will be shown as not up to date, but it is tho.

**Comment by kentcdodds** [comment]
As mentioned:

> Could probably use some of the logic we use [here](https://github.com/kentcdodds/glamorous-website/blob/83c98ee6d0f9c81230b83905f3a6dcef9f967ba1/other/list-l10n.js#L23-L38)

So we basically say: "If the english translation change date is newer than the locale's change date, then it is outdated"

It's imperfect, but it's better than nothing I think.

**Comment by kentcdodds** [comment]
Ok, so I've extracted the logic, all we need to do is use [this function](https://github.com/kentcdodds/glamorous-website/blob/master/other/translation-status.js) right around [here](https://github.com/kentcdodds/glamorous-website/blob/43c64cbb791f0b0cfc3992bdc62a74c1b9805d7c/other/babel-plugin-l10n-loader.js#L83-L88) to assign a `translationStatus` if it's not the `fallbackLocale`, then we can use that in the UI [hereish?](https://github.com/kentcdodds/glamorous-website/blob/43c64cbb791f0b0cfc3992bdc62a74c1b9805d7c/components/docs-page.js#L108) to show a link (if a translation's needed, or outdated) to the translation file.

**Comment by kentcdodds** [comment]
I'm going to start working on this :+1:
