### ISSUE TITLE
Conventionalize the page content files

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#228]
**Problem Description:**

We should probably list out our page sections like styled-components does:

![screen shot 2017-07-11 at 9 15 12 pm](https://user-images.githubusercontent.com/1500684/28100228-0c6c4fb0-667e-11e7-833b-b6c056ba73d3.png)

(Both a special page for it as well as on the left-hand nav)

But we can't do that without hard-coding them and/or requiring the files in the Nav component which would result in all the content being loaded on all pages.

**Suggested Solution:**

If we used a convention for the name of the files that simply indicated their order that would be enough. For example, on the examples page the files would be:

```
1-css-grid.md
2-style-overrides.md
3-button.md
```

Then we could use [`babel-plugin-preval`](https://github.com/kentcdodds/babel-plugin-preval) to read the file order from disc, get the title from the metadata at the top, and add that to a list. All at build-time, all localized, all magical ✨ 

I'm not going to make this a requirement for initial release though. We've got plenty of other things to do and I want to get this released!

**Comment by motleydev** [comment]
I've had similar issues in the past where I've used an "order" prop in the front-matter of the content file. Is there any reason you'd prefer doing this with the filename?

**Comment by kentcdodds** [comment]
I like using the filename because you don't have to open the file to know the order. Makes it easier to avoid having two files with the same number. Though I guess we could throw an error if we find that or something 🤔

**Comment by kentcdodds** [comment]
Re-ordering things would probably cause issues with translations I think, so I'm going to solve this a different way.
