### ISSUE TITLE
Check accessibility

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#23]
In particular, we should verify color contrast and font sizes are accessible :+1: we already have `eslint-plugin-jsx-a11y` which is really helpful for many things. Would be great to just make sure our design is accessible to people :+1:

**Comment by mwickett** [comment]
I've opened #66 to address a11y issues. 

Largest issue was related to color - which means that the design changes, which is always a challenge. Definitely not trying to step on toes here, but I made some choices on modified color that meeting AA requirements, but don't tear apart the design (which looks fantastic!)

This is my second (I think) OSS PR, and your fantastic level of structure and process is new to me, so if I've missed something, let me know and I'll update.

Look forward to discussing!

**Comment by chrisdemars** [comment]
Are there any other a11y issues. I would be happy to test and help make improvements where I can.

**Comment by kentcdodds** [comment]
Awesome! Thanks! You can look at what we've got now at https://rc.glamorous.rocks

Or you can look at the current pull request and see the link to the staging URL (I'm the github statuses) to see what that looks like 👍

**Comment by chrisdemars** [comment]
Thanks Kent. Happy to help wherever.

**Comment by mwickett** [comment]
Three outstanding issues that I'm aware of:

1. The 'home' (`href="/"`) link that is wrapped around the lipstick icon in the nav needs some text (that should be hidden visually)
2. The example code on the front page - I *think* the syntax highlighting is Prism, but a lot of those colors aren't compliant, and need to be updated, but I can't find the style code for that.

**Comment by kentcdodds** [comment]
Maybe @philpl can help us with the example code thing that's using react-live. Any way to change the color scheme to be more accessible?

**Comment by philpl** [comment]
@mwickett The default for react-live is really minimal and admittedly bad 😆 

You can disable the default stylesheet on the provider with the `mountStylesheet` prop set to `false`. https://github.com/FormidableLabs/react-live#liveprovider- 

Then you should add this CSS code for `.prism-code` somewhere else – preferably with glamorous, I guess: : https://github.com/FormidableLabs/react-live#liveprovider- 

And after you can add some custom themes from here: https://github.com/PrismJS/prism-themes

:tada: (btw Atom Dark is nice)

**Comment by mwickett** [comment]
Thanks @philpl - I'll dig into this later today.

Just FYI for others, I've updated my PR ( #66 ) to include some small color tweaks and a fix for the non-compliant 💄 home link in the nav.

**Comment by chrisdemars** [comment]
I was going to add an alt attribtue to the lipstick icon in the nav. Tried
it locally but it never showed up. Still working on it.

**Comment by mwickett** [comment]
Thanks @philpl for your guidance on this.

//*Not directed specifically at @philpl*

I've stripped the default styling and changed the preview background to the project `blue` to match the installation code snippet color as discussed with @paulmolluzzo. 

Now we just need to load a theme, and/or make our own (which wouldn't be that hard)

This is where my lack of experience with React and Glamorous comes in - is there an accepted approach for loading a standalone external stylesheet? (Say for [Atom Dark](https://github.com/PrismJS/prism-themes/blob/master/themes/prism-atom-dark.css) :))

Thanks for any guidance here.

**Comment by kentcdodds** [comment]
Going to go ahead and close this for now. Let's just keep an eye on things.

**Comment by chrisdemars** [comment]
Sounds good
