### ISSUE TITLE
Fix the website

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#237]
It's broken: https://rc.glamorous.rocks/

![screen shot 2017-07-15 at 10 55 59 pm](https://user-images.githubusercontent.com/1500684/28244752-ca7c32f6-69b0-11e7-94e7-7773f5ff76bd.png)

The problem fixes itself if I comment out [this algolia `docsearch` code](https://github.com/kentcdodds/glamorous-website/blob/d1ec291df19b90096e51c1e15ea3ef1974d684ed/components/algolia-config.js#L33-L41). [The error link](https://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=34) says:

```
Unable to find element with ID 34.
```

ID 34 is the input element.

This issue is reproducible locally if you run the full build and serve the built site:

```
npm start build.en
http-server out/en
```

Not reproducible in dev mode.

Any help appreciated :smile:

**Comment by luke-john** [comment]
just had a quick look and it appears to be a race condition with that script. will open a pr shortly.
