### ISSUE TITLE
Translate website into French

### ISSUE THREAD

**Issue by iGitScor** [kentcdodds/glamorous-website#239]
**Problem Description:**

To have a multilingual website to enable many people to use this project more effectively.

**Suggested Solution:**

To translate this site into French 🇫🇷

- [ ] `pages/_document`
- [ ] `pages/advanced`
- [ ] `pages/api`
- [ ] `pages/basics`
- [x] `pages/examples`
- [ ] `pages/getting-started`
- [ ] `pages/integration`

**Comment by iGitScor** [comment]
I'm working on it

**Comment by kentcdodds** [comment]
Wonderful!

**Comment by luke-john** [comment]
Hey @iGitScor thanks for doing the work on getting these docs translated to french. ❤️ 

I've just updated the english documentation for the typescript definitions, unfortunately my french is not good enough to update the translation.
