### ISSUE TITLE
The rc Website can't be reached

### ISSUE THREAD

**Issue by luke-john** [kentcdodds/glamorous-website#241]
**Problem Description:**

When visiting https://rc.glamorous.rocks/ chrome gets the following error.

```
This site can’t be reached

The web page at https://rc.glamorous.rocks/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_PROTOCOL_ERROR
```

![image](https://user-images.githubusercontent.com/848525/28267509-e20c8cfe-6b2c-11e7-9b59-18943f0ebb41.png)

**Suggested Solution:**

**Comment by luke-john** [comment]
Look like it's resolved itself? might have been an issue with the now hosting ¯\_(ツ)_/¯.

**Comment by kentcdodds** [comment]
Yeah, I noticed that this morning too and fixed it with [this weird guide](https://usefulpcguide.com/18302/fix-err_spdy_protocol_error-google-chrome/) (specifically step 3). No idea what's up there 😖
