### ISSUE TITLE
Broken link in the documentation

### ISSUE THREAD

**Issue by iGitScor** [kentcdodds/glamorous-website#243]
Hi,

**Problem Description:** There is a broken link for a deployed app example.
Broken link: https://with-glamorous-zrqwerosse.now.sh

**Page:** https://rc.glamorous.rocks/integrations/#next.js(https:github.comzeitnext.js) (section `next.js`)

**Suggested Solution:** If there is another example, switch links, otherwise, change the content

**Comment by kentcdodds** [comment]
Thanks @iGitScor! Anyone can feel free to deploy that example and update the URL 👍
