### ISSUE TITLE
Upgrade react-live or implement TabGate

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#254]
**Problem Description:**

[React-live isn't very accessible](https://github.com/FormidableLabs/react-live/issues/19)

**Suggested Solution:**

Make our own implementation of [TabGate](https://github.com/FormidableLabs/react-live/blob/e0551d7d9a00f40105629fcc6df05b5d38792c34/demo/components/TabGate.js) or help get [this merged](https://github.com/FormidableLabs/react-live/pull/23) and released so we can update.

I want to do this before we release.

**Comment by paulmolluzzo** [comment]
What if we make a global keyboard shortcut to bind `esc` to trigger a `click` event on the document body? Wouldn't that work?

**Comment by kentcdodds** [comment]
That's a good point! We'd want to add a note somewhere by all the react-live samples and have a screenreader mention that's possible, but that shouldn't be terrible :+1:

**Comment by paulmolluzzo** [comment]
I'll try to get to this tonight or one night this weekend. (I've been busy lately and haven't had much time for OSS. 😔)

I believe I see an issue with this solution: We'll never be able to tab past the first react live instance. `esc` will effectively put you back to the beginning of the document WRT tabbing. IDK for sure though. 🤔

**Comment by burge-is** [comment]
Here's what may be a better iteration of [TabGate](https://github.com/burge-is/react-live/blob/fe1242497dd90cb847009d54b7daab3b5094c6df/src/components/Editor/TabGate.js) for react-live (no dotted outline). Just did some testing on it and didn't notice any issues.

[This](https://github.com/FormidableLabs/react-live/pull/23) current iteration of the other PR mentioned is currently exhibiting undesirable behavior when switching focus with mouse clicks.

![focus styling issue](https://user-images.githubusercontent.com/6237202/28740903-95033484-73d9-11e7-9549-24e54eda9559.gif)

In the early parts of the gif that is me holding the mouse down, which causes the live editor that is losing focus to be styled as if it were the focused element (cause it is) before it loses that status on `mouseUp`. 

It's a race condition between `blur `adding the class of `tab-guarded` (a class which introduces an outline style when focused) and `mouseUp `shifting focus to another editor. A possible solution for this is to not remove the outline whilst editing, akin to how text areas handle it... like this text area I am currently typing inside of. This would eliminate the funny trailing focus.

**Comment by kentcdodds** [comment]
I think what you have in that gif is great and I'd love it if you could submit a pull request 😍❤️

**Comment by burge-is** [comment]
That behavior is the current state of the existing PR.

**Comment by kentcdodds** [comment]
Oh, I was talking about a pull request to this rebuilt. But if we can get that other pull request merged, that would be even better! :-)

**Comment by paulmolluzzo** [comment]
It seems that having @burge-is's PR get finished and merged into `react-live` is a preferable solution than figuring out a workaround. From the looks of the gif it's pretty close. I guess it's a question of priorities for @kentcdodds, but since the blog post is still a WIP I am guessing we still have some time to see how that PR nets out. Amirite?

**Comment by kentcdodds** [comment]
Yes agreed, and yes, we have time! 👍

**Comment by kentcdodds** [comment]
Planning on publishing things tomorrow :)

**Comment by kentcdodds** [comment]
I've taken care of this for the time being by publishing `@kentcdodds/temp-react-live` and using that. Will work for now :smile:

**Comment by knittingcodemonkey** [comment]
Has there been any movement on this? I'm looking into options for accessible and interactive code examples. This pull request would make react-live a viable option.

**Comment by kentcdodds** [comment]
You should probably ask in https://github.com/FormidableLabs/react-live/pull/23
This issue's closed because we don't need it (we're on a fork until that PR's merged or the problem's solved another way).
