### ISSUE TITLE
don't make the guide disappear when typing

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#257]
**Problem Description:**

![bad](https://user-images.githubusercontent.com/1500684/28934622-db2e5bdc-783e-11e7-8dac-a76a168376c7.gif)

This isn't a great experience. I don't think we need to do this everywhere, but at least on the guide where you're trying to type out what you see in the guide it's really annoying that it goes away.

**Suggested Solution:**

I think the best thing would be to implement this: https://github.com/FormidableLabs/react-live/issues/20

But after that if we could just do a debounce or try/catch somewhere to make it so we don't render the guide if there's a syntax error that'd be awesome.

Who wants this!? :smile:

**Comment by vernondegoede** [comment]
I'd love to help 🤠

**Comment by kentcdodds** [comment]
Awesome! Thanks! I look forward to seeing your PR :smile:

**Comment by yuanchuan** [comment]
To place `<StyledLiveError />` inside the `<RightHandSide>` will prevent the editor from jumping when errors come. 

It may help a bit until `react-live` provides an extra option to completely resolve the original issue.

**Comment by kentcdodds** [comment]
That sounds great! Could you make a PR for that @yuanchuan?

**Comment by yuanchuan** [comment]
😄 https://github.com/kentcdodds/glamorous-website/pull/272
