### ISSUE TITLE
Mixed content warnings in console

### ISSUE THREAD

**Issue by ndelangen** [kentcdodds/glamorous-website#265]
**Problem Description:**
When I visit a page and open the browser console, I am greeted by 4 wonderful warnings telling me that the secure page was unfortunately polluted by a few resources which were not served over https.

Here's what it looks like:
<img width="686" alt="screen shot 2017-08-07 at 13 46 11" src="https://user-images.githubusercontent.com/3070389/29025421-e3bca552-7b76-11e7-9906-e5e06cea6ca7.png">

**Suggested Solution:**
Make sure all resources are served over `https://`

**Comment by ndelangen** [comment]
#good-first-contribution ?

**Comment by kentcdodds** [comment]
I looked at this before I think. I'm afraid that we don't control the link because it's a redirect :-(

But maybe someone could take a look.

**Comment by paulmolluzzo** [comment]
If we want to use https://badge-size-mpcfddqqgp.now.sh/ it will work, but I opened an issue on the `badge-size` repo to upgrade to `https`. 🤞

**Comment by M-ZubairAhmed** [comment]
I dont know if it solves the problem but i looked into that code and changed http to https? Will this help
(I am sorry for being naive, this is my first)

**Comment by kentcdodds** [comment]
Thanks @M-ZubairAhmed,
The problem is that even if we change our use from `http` to `https`, the service that does the redirect will redirect it to `http`. @paulmolluzzo's example seems to fix this problem. I think everything will be better as soon as [this issue](https://github.com/ngryman/badge-size/issues/62) is resolved.

Thanks!

**Comment by M-ZubairAhmed** [comment]
oh yes I have seen that issue, thank you.

**Comment by paulmolluzzo** [comment]
badgesize.io just upgraded to `https`, which resolved this for us!

https://github.com/ngryman/badge-size/issues/62#issuecomment-382075277

**Comment by kentcdodds** [comment]
Hooray!
