### ISSUE TITLE
Remove usage of glamor insert for adding multiple rules

### ISSUE THREAD

**Issue by luke-john** [kentcdodds/glamorous-website#279]
**Problem Description:**

The website is currently using glamors insert api to add multiple rules, whilst this appears to be working, this api is only meant to take a single rule and would not work if glamor was in production mode according to the [documentation](https://github.com/threepointone/glamor/blob/master/docs/api.md#cssglobalselector-style-cssinsertcss).

https://github.com/kentcdodds/glamorous-website/blob/ab11c84d0e52a8e07a6c3811debf31efbdae93b6/styles/base.js

**Suggested Solution:**

Add this template string without using glamors insert method to the page templates.

**Related:**

https://github.com/paypal/glamorous/issues/325#issuecomment-328941245

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see [the glamorous README](https://github.com/paypal/glamorous) for more information.
