### ISSUE TITLE
Failing tests on newly pulled down repo

### ISSUE THREAD

**Issue by andrew-codes** [kentcdodds/glamorous-website#283]
**Problem Description:**
When running `npm start validate` on a freshly pulled down repo yields failing tests. Running the `npm start test` command shows failed tests with a more descriptive error message.

`npm start validate` CLI output
![2017-10-20_13-28-59](https://user-images.githubusercontent.com/1578436/31834177-204da80a-b59b-11e7-9b91-c3026223ae06.png)

**Environment**
- OSX
- node@8.7.0
- npm@5.4.2

**Suggested Solution:**
Speaking to others online, it seems not everyone has this issue. Due to this, I suspect it may be environmental; possibly relying on a globally installed package or having a globally installed package that interacts in some way.

**Comment by kentcdodds** [comment]
Hmmm.. Yeah, that's weird. It looks like `babel-macros` is failing to be included in the transforms babel's using when running the tests. I'm not sure why though... I'll come back to this if I ever have time 😢

**Comment by andrew-codes** [comment]
Ok, I will investigate further. I wanted to be sure I didn't miss a step but sounds like it could be an issue. I'll dig a bit deeper and see what I can find.

**Comment by kentcdodds** [comment]
Thank you @andrew-codes!

**Comment by Shayla303** [comment]
I had the same issue pulling the repo down. You  do npm install and then do an npm install node as well. It updates the dependencies calling on the older version of node. I am on a mac and this solution worked for me. 
<img width="657" alt="solution" src="https://user-images.githubusercontent.com/24359681/35783318-5405d2d2-09c2-11e8-9dc0-ae68a9c1c0a8.png">

I have issues running the start with nps, which I will work on figuring out as well.

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see [the glamorous README](https://github.com/paypal/glamorous) for more information.
