### ISSUE TITLE
Change the favicon

### ISSUE THREAD

**Issue by iamrudra** [kentcdodds/glamorous-website#29]
Problem description:
The current favicon is too tiny to make sense out of - Neither the lipstick nor the name is visible. I feel it is because of the too too much surrounding white space.

Suggested solution:
Can we use one of the other logos that we have - The lipstick with g on the side or the background, etc? Or just the lipstick with the braces?

**Comment by kentcdodds** [comment]
Yeah, let's use this one:

![compact](https://cloud.githubusercontent.com/assets/1500684/26653431/578e2c9a-4610-11e7-9450-08263ffa84eb.png)

Maybe crop out all the extra whitespace. Would actually look better transparent. Maybe @Connorelsea can provide us with a transparent version?

**Comment by iamrudra** [comment]
I can extract a transparent one from the source files that were provided in #21

**Comment by kentcdodds** [comment]
Yup, I wonder whether @Connorelsea could provide source files like that. Pretty neat!

**Comment by paulmolluzzo** [comment]
Honestly, I think a pink square is fine. Does anyone want to take this on? @iamrudra?

**Comment by iamrudra** [comment]
@paulmolluzzo - Waiting on @Connorelsea to share the design assets and I can take this on.

**Comment by iamrudra** [comment]
Good job @kentcdodds 

Sorry I was still under the impression that we are waiting on the source files... :o

**Comment by kentcdodds** [comment]
Yeah, it's fine, I just decided I wanted to get _something_ done that's better. Still happy to get the other logo in if someone wants to make it :)

**Comment by iamrudra** [comment]
Scraped this from the other design file. made it transparent, set the correct dimensions and then tinified it - 

![icon](https://user-images.githubusercontent.com/12117759/26953753-1e65d966-4c61-11e7-9ed4-906f4c1f56f8.png)

**Comment by kentcdodds** [comment]
Super! I think that'll work great. Why don't you size it down to 128x128. I'm sure that'll handle all the cases we need it to :+1:

Thanks!

**Comment by iamrudra** [comment]
Sure. I followed the current one that you had which was 580x580. I will create the PR tomorrow with the updated dimensions.
