### ISSUE TITLE
Deploy is not working

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#293]
And I'm totally losing patience with this thing. At first the yarn install stalled, so I removed yarn and npm worked. But now the deploy is failing and I have no idea why and I don't really want to deal with it anymore. Feeling pretty fed up. All I wanted to do was deploy the unmaintained message. If someone else could figure out what's up that'd be cool.

I've built things locally and it appears that there are no index.html files generated. I thought that they were supposed to be 🤔 I'm pretty confused.

**Comment by paulmolluzzo** [comment]
I can take a look, but not until at least tonight, sorry.

If there’s any error message that might help debug this please share.

**Comment by kentcdodds** [comment]
Nothing more than what you can see in the travis build.

**Comment by paulmolluzzo** [comment]
Pushed a debugging commit directly on `master` just to get some more info, but even that wasn't a success 😕

Any chance the token is invalid? The `UnhandledPromiseRejectionWarning: [object Object][object Object]` doesn't tell me much of anything.

Relevant part of the logs for reference

```
[build] â–² Now production deployment pending: https://travis-ci.org/kentcdodds/glamorous-website/builds/382682127
[build] spawning shell with command: now --token NOW_TOKEN --no-clipboard --public
[build] https://es-glamorous-etkpcjinok.now.sh
[build] > Error! Upload failed
[build] 
[build] > Error! Unexpected error. Please try again later. (Response error)
[build] 
[build] (node:4207) UnhandledPromiseRejectionWarning: [object Object][object Object]
[build] (node:4207) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[build] (node:4207) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by paulmolluzzo** [comment]
OK, I'm pretty convinced it's just something up with the `now` service. I can't even deploy a simple html file. https://test-xjfoyjcrua.now.sh/

A basic attempt at deploying a single locale fails locally:

```
[~/open-source/glamorous-website/out/en] (master) $ now 
> Deploying ~/open-source/glamorous-website/out/en under p
> Ready! https://en-hiqyelgtye.now.sh (copied to clipboard) [2s]
> You (p) are on the OSS plan. Your code and logs will be made public.
> NOTE: You can use `now --public` to skip this prompt

> Error! Upload failed
> Error! Unexpected error. Please try again later. (Response error)
```

I emailed Zeit to ask about this, but I say we just try trying again in a couple days. Just clicking rebuild in travis should do the trick I would think.

**Comment by kentcdodds** [comment]
Thanks for looking into this! I'll remind myself in a few days.

**Comment by kentcdodds** [comment]
I'm unable to dedicate any more time to this effort considering glamorous has been deprecated and there's a deprecation message now. I'm going to leave things as they are and archive the repo.

Thanks everyone who helped make glamorous the amazing thing it was <3
