### ISSUE TITLE
autoscale main deployment

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#38]
Right now the production deployment will freeze after an hour of inactivity. That's kinda annoying. So I have to do `now scale https://rc.glamorous.rocks` every time there's a new deploy if I don't want it to freeze. By the time the website is live, I don't want to have to do that with `https://glamorous.rocks`. Let's automate that (just for the production deployment).

**Comment by paulmolluzzo** [comment]
We can avoid the need to autoscale by exporting a static version. I think the site will work just fine as a static build. See here: https://github.com/zeit/next.js/blob/v3-beta/readme.md#static-html-export

`now` won't sleep a static site. There was a recent blog post or something about this specifically but I can't find it on mobile.

Or you can add a `post-build` command for Travis to run that does the autoscale command.

**Comment by paulmolluzzo** [comment]
Here's the blog post: https://zeit.co/blog/scale

> Note that static deployments never sleep, are automatically scaled and are free on all plans!

**Comment by kentcdodds** [comment]
That's cool! So would we create a static build for every locale? Since we're server-rendering the docs with the locales (that's all still a bit of a mystery to me honestly).

**Comment by paulmolluzzo** [comment]
Um, let's leave the locale thing for now. I really need to get my thoughts down for everyone so we can discuss, I've been busy, sorry. I have two ideas, and both would work with a single static deployment since we'd just be handling the logic with `state` or parsing the `pathname` (or both).

Ideally we can have a single static deploy. This site should be super fast and have a small bundle if possible.

**Comment by kentcdodds** [comment]
That all sounds awesome. Thanks!

**Comment by kentcdodds** [comment]
I think that this actually is happening automatically. I've gone to `rc.glamorous.rocks` at random times and it's always loaded very quickly, so we're good I think!
