### ISSUE TITLE
Nav <a>s don't have hrefs

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#39]
Not sure why this is.... But it makes them inaccessible to the keyboard.

**Comment by paulmolluzzo** [comment]
This has to do with the way we're using `next/link` in the `styled-links`. `next` doesn't put the `href` on the anchor tag.

We can put it on there ourselves, but we might lose prefetching. I'm not sure. 🤷🏻‍♂️

See here for docs: https://github.com/zeit/next.js/blob/v3-beta/readme.md#with-link

This is worth making an issue about in `next` I think as it's a big a11y issue.

**Comment by kentcdodds** [comment]
For anyone looking at this, you can verify this by going to [the deployment](https://rc.glamorous.rocks/) and seeing the code [here](https://zeit.co/kentcdodds/glamorous-website/mtyihznjqw/source?f=components%2Fnav.js&redirect=1).

**Comment by rockchalkwushock** [comment]
@kentcdodds the `here` link gives a 403 is it suppose too or is that the issue you are talking about here with `next/link`?

**Comment by kentcdodds** [comment]
It's that the render anchor tags don't have an href attribute which means they're not accessible by the keyboard.

**Comment by paulmolluzzo** [comment]
@kentcdodds the source code for the deployments are not public, FYI. The links to source you left above are 403s for everyone but you. 😉

Open this in incognito: https://zeit.co/kentcdodds/glamorous-website/mtyihznjqw/source?f=components%2Fnav.js&redirect=1

**Comment by rockchalkwushock** [comment]
ah duh I did the same thing not realizing that `public` is set to `false` by default when on any plan above OSS. Thanks @paulmolluzzo

**Comment by kentcdodds** [comment]
Whoops! Haha, here's the file with the link components: https://github.com/kentcdodds/glamorous-website/blob/master/components/nav.js

**Comment by rockchalkwushock** [comment]
@kentcdodds  @paulmolluzzo 

I'm going to look into a work around tonight on this &/or take a look at the `next/link` code and see what might be able to be done to achieve this.

**Comment by paulmolluzzo** [comment]
@rockchalkwushock we can add the `href` to the anchor easily in that component, but I don't know if it'll affect the prefetching provided by `next`. If you try you should see network requests when hovering over the links. That's the prefetch happening.

**Comment by rockchalkwushock** [comment]
@paulmolluzzo ok I will look into it a little later tonight to see if the prefetching is affected when doing this.

**Comment by kentcdodds** [comment]
Thank you so much!

**Comment by paulmolluzzo** [comment]
🎉 Thanks @rockchalkwushock!

**Comment by paulmolluzzo** [comment]
Looked at this last night and didn't see network requests like I said would be there. I must be wrong about how prefetching works. 🤔

I can confirm that moving the `href` makes the links accessible through the keyboard (tabbing) and doesn't reduce anything. Maybe we just want to go for it?

**Comment by paulmolluzzo** [comment]
https://zeit.co/blog/next#anticipation-is-the-key-to-performance

> For www.zeit.co we've implemented a technique on top of Next.js that brings us the best of both worlds: every single <Link prefetch /> tag pre-fetches the component's JSON representation on the background, via a ServiceWorker.

Yeah, I was wrong. 🙊

**Comment by kentcdodds** [comment]
Oh, neat! So it's just a matter of adding an `href` now? Cool. Let's do that :D

**Comment by rockchalkwushock** [comment]
Sorry I didn't get back last night on this. I had found that the `hovering on the link` was not doing the prefetching and that it was being done as soon as the page was loading. I was too tired to keep looking. Great find!

**Comment by paulmolluzzo** [comment]
Yeah, we can add it in the `styled-links.js` here: https://github.com/kentcdodds/glamorous-website/blob/master/components/styled-links.js#L37

We need to add `href={href}` to the `StyledAnchor`.
