### ISSUE TITLE
Add Service Worker

### ISSUE THREAD

**Issue by ooade** [kentcdodds/glamorous-website#44]
I can help with sw-precache-webpack-plugin???

**Comment by kentcdodds** [comment]
Sounds cool! I've never used now/next.js before so I'm learning as I go. I'd love the docs to be available online though! I've also never used sw-precache-webpack-plugin before. I've always used the offline-plugin. But in any case, if you want to work on adding a service worker to the site, I'd totally love that! Thanks!

**Comment by ooade** [comment]
I never got offline-plugin to  [~work with Next.js~](https://github.com/zeit/next.js/issues/861). But, i was able to make it work with [sw-precache-webpack-plugin](https://github.com/ooade/NextSimpleStarter) which is [what styled-component's website adopted](https://github.com/styled-components/styled-components-website/blob/master/next.config.js#L37). BTW, since you love the docs online, we could just add the networkFirst option to all urls, so it tries fetching from the network first then fallback to the service worker on timeout.

**Comment by kentcdodds** [comment]
That sounds great :+1: Thanks!

**Comment by ooade** [comment]
We would be needing a server to send our service worker file. Should i create a simple server with express or we should forget about the service worker?

**Comment by kentcdodds** [comment]
Hmmm... I'm unsure what you mean. This is using next.js which is a server right?

**Comment by kentcdodds** [comment]
Also, I'm pretty sure the service worker file is just static. Why would we need a special node server to serve it?

**Comment by ooade** [comment]
Just what i wanted to say; Static files are served via `/static/` but we need our service worker scope to be one level up i.e `./` so that it can match all content.

**Comment by ooade** [comment]
P.S: Scope and worker must be in the same location

**Comment by kentcdodds** [comment]
Ah, right, makes sense. So would we make a server.js look the example you linked to? Then does next run that server for us? What infrastructure changes do we need to make?

I'm really excited about this!

**Comment by ooade** [comment]
Yeah, Yeah, and nothing much :sweat_smile: We just need a simple server to serve us the service worker. I was just asking for your permission to add express or something simpler since we only need it that purpose :smile:

**Comment by paulmolluzzo** [comment]
`next` is running a node server when you run `next start` so I'm not sure we need to add `express` at all. I would just update the webpack config to include the service worker and try pinging `/sw.js`. It should work from what I can tell.

Also, if we start using `express` or need to keep the `next` server running that means we can't do the static export I mentioned in #38, so we'll need to also do that auto scaling stuff on deploys to ensure there's no sleeping or the server.

**Comment by paulmolluzzo** [comment]
Another note, if by "serving" the JS file we mean baking bake to GET it, a static build/export on now should work too. It won't execute and code on a server, but it will use `serve` to serve the files we deploy. If all we need to do is respond to a GET with that file then a static build should be OK I think. Looking at the example @ooade made that seems to be the extent of it.

**Comment by kentcdodds** [comment]
Sounds like with the static export we could have a pay bills step to just stick the sw file in the right place when it's done 🤔

**Comment by paulmolluzzo** [comment]
That might work too. I'd like to shoot for a static export because we (@kentcdodds really) gets free autoscaling. We don't really need anything to be done server-side, so why not? (I'm also a sucker for static sites 😁)

**Comment by ooade** [comment]
@paulmolluzzo isn't static export a v3 beta thing? But anyhow it is, just lead me and i'll take it up from there :sweat_smile:

**Comment by paulmolluzzo** [comment]
@ooade you're right, it's in the beta. I guess let's try to implement without addding in an `express` server and ignore the static export aspect for now?

**Comment by ooade** [comment]
Yeah, that sounds nice

**Comment by ooade** [comment]
Bin busy with school lately, @paulmolluzzo how do you suggest we approach this??? Or we wait for v3??

**Comment by kentcdodds** [comment]
I think I heard v3 will be released soon. Not sure what that means in terms of days, but I expect we could upgrade our version to the v3 alpha and be ok.

**Comment by ooade** [comment]
Things seem to work fine with http-server, just like the one [Next.js implemented](https://github.com/zeit/next.js/blob/v3-beta/server/index.js)

Tested it on [a repo](https://github.com/ooade/NextSimpleStarter/blob/master/server.js)

![autoscaling](https://user-images.githubusercontent.com/11811904/27518475-bbbe6c80-59d8-11e7-9865-d5f12a72ca05.png)

So, we can still leave v3 for now :)

**Comment by kentcdodds** [comment]
Get this! We're on v3 (beta) now and the static export works really well! I think we're ready to go! Pretty sure we just need to have something [here](https://github.com/kentcdodds/glamorous-website/blob/master/package-scripts.js#L16) to copy the sw.js file right?

**Comment by ooade** [comment]
Having issues serving js files via static export. Maybe @paulmolluzzo can help with this :sweat:

**Comment by kentcdodds** [comment]
Hmmm... I was thinking that we could just copy the service worker file to each of the build directories. Or is it not that simple?

**Comment by kentcdodds** [comment]
This project is now in an unmaintained status. Please see [the glamorous README](https://github.com/paypal/glamorous) for more information.
