### ISSUE TITLE
Add "edit" button to every page section 

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#47]
So we can encourage folks to contribute improvements to the docs. Probably want to just have some subtle icon at the top of each [section](https://github.com/kentcdodds/glamorous-website/blob/69ed6e8e2d70b2f894954bdf187260679db771b4/components/page-sections.js#L24) that links to the github `/edit` URL for the relevant file, [for example](https://github.com/kentcdodds/glamorous-website/edit/master/translations/en/api/glamorous.js).

**Comment by paulmolluzzo** [comment]
Closed by #46
