### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by paulmolluzzo** [kentcdodds/glamorous-website#5]
There is a URL `/docs` that we'd like to populate with documentation. The documentation that we have now is all piled into the [README of `glamorous`](https://github.com/paypal/glamorous/blob/master/README.md).

Ideally the documentation we store will be in markdown to make it easy or other people to contribute.

Since there is no content just yet, there's a lot of flexibility on how to structure this. It might be worth creating a directory like `docs` and then putting the markdown files in there. Then we can load the markdown files into the `/docs` page.

An idea I have is to split the documentation up into separate files like according to the headers. From there we might have an easier time supporting searching and direct linking to topics through query params.

**Comment by liadbiz** [comment]
@paulmolluzzo yeah, this is what I am planing to do, actually some works have been done.
my plan about /docs stucture: 
+ basics
  + install.md
  + get_started.md
  + core_concepts.md
  + props.md
  + theme.md
  + context.md
 ...
+ guide
  + size.md
  + animation.md
  + media_query.md
  + server_rendering.md
  + helper_function.md
...
+ api
  + api.md

I have made a experimental [repo](https://github.com/liadbiz/glamorous-notes)

@kentcdodds  need you thoughts here! :100:

**Comment by paulmolluzzo** [comment]
@liadbiz please take a look at #9 and let me know your thoughts. Maybe we can get it sorta working with one file, merge it, then you can split it up and get the other files with individual routes and a subnav working?

**Comment by kentcdodds** [comment]
@liadbiz, I like that structure. Though for the `api` it may be useful to split it out into multiple pages because the API is kinda big. But maybe not 🤔

**Comment by kentcdodds** [comment]
Alrighty, so after a lot of trial and error, I got Crowdin set up on the repo. You can see the project [here](https://crowdin.com/project/glamorous-website). [Here](https://www.youtube.com/watch?v=F69lAvAKxE4) is a promo video that explains what crowdin is.

So now we need to break up the `main.md` file into smaller bits for all of the pages that we want and start working on the basics/guide/integrations/etc. as well.

We need all the help we can get! I'll create the files that I think we'll need, then I'll ask people to help fill in the files with content.

**Comment by kentcdodds** [comment]
Ok, I think that we're ready to start getting help from folks. A lot of stuff can be pulled out of [the glamorous README.md](https://github.com/paypal/glamorous/blob/master/README.md) and [the examples](https://github.com/paypal/glamorous/tree/master/examples).

You know what... I just thought... I wonder if crowdin could work with a file like this:

```javascript
import Markdown from './some-markdown-component'
import CodeExample from '../some-comonent-or-something'
export default Docs

function Docs() {
  return (
    <div>
      <Markdown>
        {`
          Here is the markdown text stuff, this is what should be translated
        `}
      </Markdown>
      <CodeExample />
      <Markdown>
        {`
          Here is the markdown text stuff, this is what should be translated
        `}
      </Markdown>
    </div>
  )
}
```

If that's possible, that'd be pretty awesome. I'm going to look into that really quick.

**Comment by kentcdodds** [comment]
Ok, so that's not going to work very well I'm afraid...

![bad-maybe](https://cloud.githubusercontent.com/assets/1500684/26652322/c3103f66-460c-11e7-8934-6f0f13519998.gif)

**Comment by kentcdodds** [comment]
So it seems to me that we'll need to come up with some way to load the markdown and dynamically swap bits out of it for whatever we want. I don't think that'll be impossible. Something like:

```markdown
# This is the page

Here is some content

{EXAMPLE_THING}

Here is more content
```

Then we'd do something like:

```javascript
import ourFancyMarkdownThing from './our-fancy-markdown-thing'

const MarkdownComponent = ourFancyMarkdownThing('./path-to-markdown.md', {
  EXAMPLE_THING: (
    <div>whatever we want</div>
  )
})

export default MarkdownComponent
// <MarkdownComponent /> renders the markdown with our EXAMPLE_THING
```

I think that `ourFancyMarkdownThing` would dynamically load the markdown file (render a loading thing while the user's waiting) and interpolate the `EXAMPLE_THING` into the resulting HTML. We do something similar at my work and it seems to work pretty well. Thoughts?

Oh, and I just remembered @paulmolluzzo mentioned wanting to server render the docs. Let's push that onto something we can do after the release.

**Comment by kentcdodds** [comment]
We might also do something like:

```md
# Here's our page

\```jsx <-- an attempt to escape triple `
const Button = glamorous.button({})
render(<Button />)
\```
```

And then replace any code block with React-Live. Thoughts on that?

**Comment by kentcdodds** [comment]
Let's open up individual issues for every bit of documentation we want so folks can jump in and help :+1:
