### ISSUE TITLE
[meta] Add labels to GH repo

### ISSUE THREAD

**Issue by paulmolluzzo** [kentcdodds/glamorous-website#52]
I think it'd be great to have some more labels available on this repo so we can organize tasks and make it easier for people to find something they can contribute that falls within their skill set. Off the top of my head I'm thinking:

* Good for Beginner (or "Good First PR", something to highlight tasks that don't require a ton of background knowledge)
* Documentation
* Has PR
* Under Discussion

Anything else?

**Comment by kentcdodds** [comment]
Ok, I made a few labels and I even created [a project](https://github.com/kentcdodds/glamorous-website/projects/1). I've never used a github project before, but maybe it'll be helpful! We'll see how it goes. Thanks!
