### ISSUE TITLE
Fixup tests

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#57]
Right now, pretty much any change is going to result in snapshots breaking. That's fine, but one thing I want to avoid is having to update the snapshots for every content change. We want this to be really easy for folks to contribute to and that means being able to contribute without even pulling down the repo and just using the GitHub editor for updating content.

I'm unsure of the best way to solve this. I just don't want to have to update snapshots every single time there's a content change.

**Comment by paulmolluzzo** [comment]
Can we reduce the tests to not render the content from the markdown? Will `shallow` from `enzyme` do that for us?

**Comment by kentcdodds** [comment]
Yeah, maybe this is a good use case for `shallow`. Even though [I'm not normally a huge fan](https://www.briefs.fm/3-minutes-with-kent/49). 👍

**Comment by kentcdodds** [comment]
I'm going to go ahead and just push this so we don't worry about merge conflicts from anyone else wanting to work on things.

**Comment by kentcdodds** [comment]
This is actually pretty neat. Because the snapshot was so huge I never even reviewed it, so all confidence I was getting was that it didn't throw errors. Now we don't have the snapshots issue, but we're still confident that it doesn't throw errors. And we have the same amount of coverage :) Yay.
