### ISSUE TITLE
Complete Site Design; Use Theme Provider

### ISSUE THREAD

**Issue by paulmolluzzo** [kentcdodds/glamorous-website#6]
The site's design could use lots of attention, and while it's being done we may want to move global style choices (colors, typography, etc) into a `ThemeProvider` and then use the `ThemeProvider` in the `layout` component.

Further, there is a mix of uses of `glamorous` in this site. There are `inline` component definitions and `glamorousComponentFactory` definitions, which makes it a little harder to find your way around the codebase. We may want to lean towards one method for the sake of coherence and legibility, and in consideration of the use of a `ThemeProvider` it might be clearer to use `glamorousComponentFactory`.

Consider this example, where we can use the `theme` in a component to define a common color and media query.

```js
const StyledHeading = glamorous.H1((props, theme) => ({
  color: theme.colors.primary, // uses theme as single location for definitions
  fontSize: 10,

   // pulls in the query definition from theme
   [theme.mediaQueries.mobile]: {
      fontSize: 20
  }
}))

export default () => <StyledHeading>glamorous</StyledHeading>
```

**Comment by paulmolluzzo** [comment]
`ThemeProvider` was added in #16

**Comment by bulby97** [comment]
@paulmolluzzo I plan to make the homepage today, is there anyone already on it ?
Btw, what do you think about adding prettier-standard ?

**Comment by paulmolluzzo** [comment]
@bulby97 Go for it! There are designs in #8 and more info there.

You might want to open a separate issue about `prettier-standard` so we can discuss. I've never used it before.

**Comment by kentcdodds** [comment]
Actually, I'm going to set this up with `prettier-eslint` with my own config (consistent with the `glamorous` repo. Will make a PR momentarily.

**Comment by paulmolluzzo** [comment]
@kentcdodds I think we can close this ticket since most of the "core" design is done, and we still have #8 open to work from. If you agree just close out this issue. Thanks!
