### ISSUE TITLE
Add flow

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#65]
That would really help I think.

**Comment by kentcdodds** [comment]
Labeled this as a good first issue (with the caveat that it's only really good if you're experienced with flow already). It doesn't require you understand the existing codebase very well.

**Comment by bhargav175** [comment]
Hi @kentcdodds . I would like to take this up!

**Comment by paulmolluzzo** [comment]
Go for it @bhargav175! 👍

**Comment by kentcdodds** [comment]
Awesome!

**Comment by kentcdodds** [comment]
We've got this. Just need to add annotations as we go!
