### ISSUE TITLE
advanced -> theming

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#73]
Learn how to set up the project [here](https://github.com/kentcdodds/glamorous-website/blob/master/CONTRIBUTING.md) and how docs work [here](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md). For much of this you should be able to do everything without even cloning the project. You could just do it in [the GitHub editor](https://help.github.com/articles/editing-files-in-another-user-s-repository/)!

- Existing docs: https://github.com/paypal/glamorous/blob/master/README.md#theming
- Destination: https://github.com/kentcdodds/glamorous-website/blob/master/pages/advanced/content/theming.js

Anyone can work on this **Just comment here when you're going to start**. Feel free to improve the existing docs if you're copying them over (it doesn't have to be a direct copy/paste if feel you can improve upon them).

Thanks!

**Comment by raerpo** [comment]
Hi Kent, Awesome project by the way.

I been working on this issue but keep getting an error when i try to commit with `npm start commit`

<img width="825" alt="captura de pantalla 2017-06-11 a las 13 25 56" src="https://user-images.githubusercontent.com/1649463/27013030-b00c2a24-4ea9-11e7-9b3f-cc266d191221.png">

Do you know what's happening?

**Comment by TreTuna** [comment]
@rearpo This is an issue that I was facing as well. @kentcdodds said to just use a normal git commit instead so that it bypasses this script. I believe it's an issue with working on forks of the project as per issue [#99](https://github.com/kentcdodds/glamorous-website/issues/99)
