### ISSUE TITLE
advanced -> Server Side Rendering (SSR)

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#74]
Learn how to set up the project [here](https://github.com/kentcdodds/glamorous-website/blob/master/CONTRIBUTING.md) and how docs work [here](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md). For much of this you should be able to do everything without even cloning the project. You could just do it in [the GitHub editor](https://help.github.com/articles/editing-files-in-another-user-s-repository/)!

- Existing docs: https://github.com/paypal/glamorous/blob/master/README.md#server-side-rendering-ssr
- Destination: https://github.com/kentcdodds/glamorous-website/blob/master/pages/advanced/content/ssr.js

Anyone can work on this **Just comment here when you're going to start**. Feel free to improve the existing docs if you're copying them over (it doesn't have to be a direct copy/paste if feel you can improve upon them).

Thanks!

**Comment by TreTuna** [comment]
I'll take this one

**Comment by TreTuna** [comment]
Ran into the same issue that williamolojede had on the Typescript docs section used your info on the issue there to work around it here.

![glamorousssrcommiterr](https://user-images.githubusercontent.com/16496746/27103140-b0719c9e-5055-11e7-8896-f3f869a691d9.png)

**Comment by TreTuna** [comment]
[#123](https://github.com/kentcdodds/glamorous-website/pull/123)

**Comment by kentcdodds** [comment]
Really sorry about that. I'm really not sure what's going on there. 🤔 

Why don't you update your local branch and don't use `npm run commit` anymore, just commit like normal.

**Comment by TreTuna** [comment]
Updated and created new pull request [#138](https://github.com/kentcdodds/glamorous-website/pull/138)

**Comment by kentcdodds** [comment]
Thanks!
