### ISSUE TITLE
advanced -> existing CSS

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#76]
Learn how to set up the project [here](https://github.com/kentcdodds/glamorous-website/blob/master/CONTRIBUTING.md) and how docs work [here](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md). For much of this you should be able to do everything without even cloning the project. You could just do it in [the GitHub editor](https://help.github.com/articles/editing-files-in-another-user-s-repository/)!

- Existing docs: None, sorry
- Destination: https://github.com/kentcdodds/glamorous-website/blob/master/pages/advanced/content/existing-css.js (partially finished)

Anyone can work on this **Just comment here when you're going to start**. Feel free to improve the existing docs if you're copying them over (it doesn't have to be a direct copy/paste if feel you can improve upon them).

Thanks!

**Comment by paulmolluzzo** [comment]
I'm not 100% sure what we want here? Are you thinking something like this: https://twitter.com/kentcdodds/status/880854277266198528

**Comment by kentcdodds** [comment]
Bingo. All the places you can use regular class names. So that's good, also the className prop. Also, this would probably be a good example as well: https://twitter.com/kentcdodds/status/881537950361591808

**Comment by kentcdodds** [comment]
Also, the css prop can take a class name

**Comment by paulmolluzzo** [comment]
Incoming!
