### ISSUE TITLE
api -> TypeScript

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#77]
Learn how to set up the project [here](https://github.com/kentcdodds/glamorous-website/blob/master/CONTRIBUTING.md) and how docs work [here](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md). For much of this you should be able to do everything without even cloning the project. You could just do it in [the GitHub editor](https://help.github.com/articles/editing-files-in-another-user-s-repository/)!

- Existing docs: https://github.com/paypal/glamorous/blob/master/other/TYPESCRIPT_USAGE.md
- Destination: https://github.com/kentcdodds/glamorous-website/blob/master/pages/api/content/typescript.js

Anyone can work on this **Just comment here when you're going to start**. Feel free to improve the existing docs if you're copying them over (it doesn't have to be a direct copy/paste if feel you can improve upon them).

Thanks!

**Comment by williamolojede** [comment]
i'll take this

**Comment by williamolojede** [comment]
@kentcdodds the `npm start commit` keeps failing

**Comment by williamolojede** [comment]
![image](https://user-images.githubusercontent.com/23551907/27046892-c61063a2-4fae-11e7-90e1-6abc96e2d188.png)

**Comment by kentcdodds** [comment]
That's really weird. But I'm pretty sure you're not the only one to experience it. I'm not seeing it locally. Don't worry about it though, instead of using `npm start commit`, just run:

```
npm start contributors.generate
git commit -am "docs(TypeScript): add TypeScript docs" --no-verify
```

If that doesn't work, comment here again with another screenshot of the output.

**Comment by williamolojede** [comment]
that works will create a pr now
