### ISSUE TITLE
api -> glamorousComponentFactory

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#79]
Learn how to set up the project [here](https://github.com/kentcdodds/glamorous-website/blob/master/CONTRIBUTING.md) and how docs work [here](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md). For much of this you should be able to do everything without even cloning the project. You could just do it in [the GitHub editor](https://help.github.com/articles/editing-files-in-another-user-s-repository/)!

- Existing docs: https://github.com/paypal/glamorous/blob/master/README.md#glamorouscomponentfactory
- Destination: https://github.com/kentcdodds/glamorous-website/blob/master/pages/api/content/glamorous-component-factory.js

Anyone can work on this **Just comment here when you're going to start**. Feel free to improve the existing docs if you're copying them over (it doesn't have to be a direct copy/paste if feel you can improve upon them).

Thanks!

**Comment by williamolojede** [comment]
is this still available?

**Comment by williamolojede** [comment]
I'll take this if its available

**Comment by paulmolluzzo** [comment]
It's all yours. Go for it! 👍
