### ISSUE TITLE
Code Site Designs

### ISSUE THREAD

**Issue by hozefaj** [kentcdodds/glamorous-website#8]
creating wireframes with sketch so that the look n feel of the website is agreed upon.

**Comment by jonmajorc** [comment]
Here is a quick wireframe of what I was thinking styling would look like for the landing page... Let me know your feedback. This didn't take long to do, so I can always make more edits if no one is digging this look. We can always add more things to the landing page too, so let me know your feedback!
![home-page](https://cloud.githubusercontent.com/assets/7799266/26515151/84a42ddc-423d-11e7-9b1d-db8e1d74069b.png)

**Comment by kentcdodds** [comment]
Wow Jon! This is great! I love it! I wonder if we can make some of the font bigger? I'd like to avoid anything much smaller than ~16px

I wonder what @Connorelsea could add to this. He designed much of the JavaScript Air website and I was really pleased with that. And it just so happens that he's using glamorous too! Woo!

**Comment by kentcdodds** [comment]
I'm actually thinking the subtle gradient that he had on his version of the glamorous logo might go well on this page... 🤔

**Comment by jonmajorc** [comment]
Thanks kent! Font could be increased for sure! That sounds like a good plan, and Definitely! Javascript Air's website is awesome...

**Comment by jonmajorc** [comment]
@kentcdodds can you share that logo version or point me to where I can look? 🙂

**Comment by kentcdodds** [comment]
See here: https://m.imgur.com/a/0dsc3
And here: https://github.com/paypal/glamorous/pull/77

**Comment by liadbiz** [comment]
looks really good! :+1:

**Comment by jonmajorc** [comment]
Hey, with #12 are we wanting to have on the landing page a React Live to allow users to play with glamorous right away?

**Comment by paulmolluzzo** [comment]
Yes. The homepage should have installation instructions, a link/badges for the GitHub repo, and a basic example at a minimum.

**Comment by kentcdodds** [comment]
Agreed!

**Comment by jonmajorc** [comment]
Hope you all can use your imagination! 😄 1) The black box underneath glamorous would be the React Live (Probably editing something live on the page... 😉 ) 2) Used By section, if we would have one, would have the companies that use Glamorous. 3) I figure "Installation", "The Problem", and "The Solution" would be useful to have on the landing page for content 4) I did not pick out the Type Face, I am just using Roboto in this example.

![image](https://cloud.githubusercontent.com/assets/7799266/26531728/02c918d0-43b5-11e7-8122-e200f525f8cf.png)

**Comment by kentcdodds** [comment]
Love it! Some thoughts:

It feels like to much for the home page. We can probably just leave off all the badges. Installation could probably just be a single line (with a link to more info). Actually, all the stuff in the second section could maybe just go in a getting started guide 🤔

**Comment by paulmolluzzo** [comment]
This is excellent! I agree with @kentcdodds and have some general thoughts:

* I'd remove most of the badges. GitHub, npm, license, sizes. That's what people want to know i think.
* I'd ditch the square logo, we have three logo styles on the page.
* We really just need the installation and a simple example _in that order_, so I'd move the example box down.
* The tag line can be above the fold below the large logo.

Even if no one agrees with these comments, the point I'm trying to make is we should only include the stuff you need to know to give it a try and/or get it installed. It should be clear and concise, and details can get tucked into other pages.

If I get some time before other people I'll try to implement this and build out a theme according to this design (colors, fonts, etc). This is still up for grabs and discussion, but I ask that anyone who works on it leverages `ThemeProvider` So we can easily use consistent styles.

Thanks a ton @jonmajorc! 🙌 This is excellent work! 👏👏👏

**Comment by jonmajorc** [comment]
Thanks @kentcdodds and @paulmolluzzo for your feedback! I am not a designer but I am trying to fill that void! 😜 Paul, I can send more details around colors, font, and etc.. From both of your feedback I made some changes! I have three new exports! I will post them separate 😄

**Comment by jonmajorc** [comment]
![home_simple](https://cloud.githubusercontent.com/assets/7799266/26533045/d0972244-43d7-11e7-8378-43ea1869917a.png)

**Comment by jonmajorc** [comment]
![home_little_of_everything](https://cloud.githubusercontent.com/assets/7799266/26533048/de2aab56-43d7-11e7-874a-6a6a0169681d.png)

**Comment by jonmajorc** [comment]
![home_badges_no_usedby](https://cloud.githubusercontent.com/assets/7799266/26533050/e61e2ca2-43d7-11e7-9887-c2bbc8ffb645.png)

**Comment by kentcdodds** [comment]
These are all so awesome! I just realized that the `$ support` badge is on  there. That's on my repos by default but because this is a PayPal project, we should probably remove it 😅 

I'll give a little more feedback later. Looks super awesome!

**Comment by paulmolluzzo** [comment]
@jonmajorc would you mind dropping relevant measurements, colors, etc here please? We now have a `ThemeProvider` implementation and we can really start digging into the design implementation.

**Comment by jonmajorc** [comment]
@paulmolluzzo yeah for sure! let me reply tomorrow morning with everything. Its been tough getting spacing to look good in these wireframes, because the glamorous header with the logo and the "g" in the background is one resource. I did do another iteration that I forgot to share too. This one has better spacing between components.
![home](https://cloud.githubusercontent.com/assets/7799266/26567562/e2775c14-44c1-11e7-8ca0-a7255b59b881.png)

**Comment by kentcdodds** [comment]
I think I like that last one best :+1: looks sooo great!

**Comment by kentcdodds** [comment]
Though I'd probably remove all the badges still. And instead of all the `prose` in "Installation", I'd simply put the text: `npm install --save glamorous react glamor prop-types` centered and with a dark background. We could link to the getting started guide with more info.

**Comment by jonmajorc** [comment]
I like the way you think Kent! 💯 

@kentcdodds @paulmolluzzo @hozefaj @liadbiz to get started on using the `ThemeProvider` for centralizing colors and stuff, you can head over to this [link](https://www.figma.com/file/cDAmmx2RLFa6yuQq8r6cpXt5/glamorous-sketch-resources-Welcome) to get started. Let me know if you want things exported as images and etc. for convenience! 👍  Also, if you want edit rights to the resources I can send you a edit link too! Sorry if the project in Figma feels like its everywhere 😄 

![home](https://cloud.githubusercontent.com/assets/7799266/26594120/15def6ec-452c-11e7-8ae6-51085beb319b.png)

**Comment by kentcdodds** [comment]
Yes! This is the winner! I love it! Thanks for all the work you've put into this :)

**Comment by jonmajorc** [comment]
Yeah, of course! Look forward into helping more 😄 

Let's code this out! 👊

**Comment by kentcdodds** [comment]
Fantastic. Work has begun in #17

**Comment by kentcdodds** [comment]
Ok, so we've got some basic content on the `/advanced` and `/examples` pages. If we could get someone to work on making those look nice in addition to these designs that'd be awesome. You can see the deployed version of the site at: https://rc.glamorous.rocks/ :)

**Comment by kentcdodds** [comment]
Somehow this got moved to #26, so I'll close this issue :)
