### ISSUE TITLE
basics -> getting started

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#82]
Learn how to set up the project [here](https://github.com/kentcdodds/glamorous-website/blob/master/CONTRIBUTING.md) and how docs work [here](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md). For much of this you should be able to do everything without even cloning the project. You could just do it in [the GitHub editor](https://help.github.com/articles/editing-files-in-another-user-s-repository/)!

- Existing docs: I'm actually not certain what this should be... Maybe we could include the [video intro](https://github.com/paypal/glamorous/blob/master/README.md#video-intro-tv)?
- Destination: https://github.com/kentcdodds/glamorous-website/blob/master/pages/basics/content/getting-started.js

Anyone can work on this **Just comment here when you're going to start**. Feel free to improve the existing docs if you're copying them over (it doesn't have to be a direct copy/paste if feel you can improve upon them).

Thanks!

**Comment by liadbiz** [comment]
working on it

**Comment by liadbiz** [comment]
how about adding the section [The problem](https://github.com/paypal/glamorous/blob/master/README.md#the-problem) and [This solution](https://github.com/paypal/glamorous/blob/master/README.md#this-solution) in README file to this section?

**Comment by kentcdodds** [comment]
Sounds like a great idea

**Comment by tdeschryver** [comment]
> how about adding the section The problem and This solution in README file to this section?
@liadbiz have you already started adding the sections, if not I'll take this one tomorrow.

**Comment by kentcdodds** [comment]
I actually think this one's done

**Comment by tdeschryver** [comment]
@kentcdodds Getting started is indeed already done, but @liadbiz suggestion about adding `problem` and `solution` is not.

**Comment by liadbiz** [comment]
@tdeschryver Now the content of getting-started page have been rewrited by @kentcdodds , it is an interactive guide, so "the problem" and "this solution" maybe not sure to be putted in here. 
what is your idea? @kentcdodds

**Comment by kentcdodds** [comment]
Yeah, definitely want to put something in there about motivations for why the library exists and what problems it's solving... I'll give it thought...

**Comment by kentcdodds** [comment]
Ok this is done! Thanks!
