### ISSUE TITLE
basics -> animation

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#85]
Learn how to set up the project [here](https://github.com/kentcdodds/glamorous-website/blob/master/CONTRIBUTING.md) and how docs work [here](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md). For much of this you should be able to do everything without even cloning the project. You could just do it in [the GitHub editor](https://help.github.com/articles/editing-files-in-another-user-s-repository/)!

- Existing docs: The animation bit from [here](https://github.com/paypal/glamorous/blob/master/README.md#example-style-objects)
- Destination: https://github.com/kentcdodds/glamorous-website/blob/master/pages/basics/content/animation.js

Anyone can work on this **Just comment here when you're going to start**. Feel free to improve the existing docs if you're copying them over (it doesn't have to be a direct copy/paste if feel you can improve upon them).

Thanks!

**Comment by Ronolibert** [comment]
Hi! I can take this one!

**Comment by chrisdemars** [comment]
I was looking at this to start with it and I am not sure how to conribute to this issue. Is it just copying and pasting informaiton or is there a level of development involved?

**Comment by kentcdodds** [comment]
Most of it should be copy/paste. But you can improve upon things if you like. You could make a better example if you like. Just make sure you read the linked docs 😉

**Comment by kentcdodds** [comment]
And thank you!

**Comment by chrisdemars** [comment]
Lol, if I could React, even JS for that matter. Copying and pasting seems the best option ha

**Comment by TreTuna** [comment]
@chrisdemars Are you working on this one? Otherwise, I'll pick it up.

**Comment by kentcdodds** [comment]
Why don't you go ahead @TreTuna, there are many of other opportunities :)

**Comment by TreTuna** [comment]
Done. [144](https://github.com/kentcdodds/glamorous-website/pull/144)

**Comment by chrisdemars** [comment]
Yeah that is fine. I have to figure out how to work in JSX lol. Sorry.

**Comment by kentcdodds** [comment]
That's alright @chrisdemars! Whatever you can do is appreciated! :)
