### ISSUE TITLE
Add Roadmap.md

### ISSUE THREAD

**Issue by parvezk** [kentcdodds/glamorous-website#89]
Roadmap link in CONTRIBUTING.md is pointing to 404 page. Please create the Roadmap page.

**Comment by kentcdodds** [comment]
We should probably just remove that link. The roadmap is pretty much whatever we come up with and whatever's in the issues :)

Would you like to [makeapullrequest.com](http://makeapullrequest.com) to remove that?

**Comment by parvezk** [comment]
@kentcdodds Sure wil do :)

**Comment by parvezk** [comment]
I get the error when I try to add myself as contributor using below command:
`npm start "addContributor parvezk"`
Error: TypeError: Cannot read property 'scriptName' of undefined

**Comment by kentcdodds** [comment]
Whoops, that should be `npm start "contributors.add <username>"`. Could you update that too? Sorry

**Comment by parvezk** [comment]
Updated. I am unable to push my branch to remote. When I do the git push, I get the permission access denied: 
`remote: Permission to kentcdodds/glamorous-website.git denied to parvezk.
fatal: unable to access 'https://github.com/kentcdodds/glamorous-website.git/': The requested URL returned error: 403`
