### ISSUE TITLE
Console fun?

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/glamorous-website#94]
Could we do something fun like this? https://twitter.com/tharakawj/status/868411676449796096
Just for fun if anyone wants to do it.

**Comment by gillchristian** [comment]
I like this, lets pick a font :smile: 

I got all of them [here](http://patorjk.com/software/taag/#p=display&f=Alpha&t=glamorous). _Each picture has a link to the page with the font selected_.

[![ansi-shadow](https://user-images.githubusercontent.com/8309423/27024210-13346fa8-4f2c-11e7-94d9-fcb8cdaecc67.png)](http://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=glamorous)

[![big](https://user-images.githubusercontent.com/8309423/27024215-16d155ae-4f2c-11e7-9391-728b93d8e6c8.png)](http://patorjk.com/software/taag/#p=display&f=Big&t=glamorous)

[![bulbhead](https://user-images.githubusercontent.com/8309423/27024216-195f54ba-4f2c-11e7-9e0d-bed4e85ce780.png)](http://patorjk.com/software/taag/#p=display&f=Bulbhead&t=glamorous)

[![delta-corps](https://user-images.githubusercontent.com/8309423/27024219-1be4091a-4f2c-11e7-9c0d-8ef4593c165a.png)](http://patorjk.com/software/taag/#p=display&f=Delta%20Corps%20Priest%201&t=glamorous)

[![doom](https://user-images.githubusercontent.com/8309423/27024221-1e2da064-4f2c-11e7-8959-3a0df0fcd985.png)](http://patorjk.com/software/taag/#p=display&f=Doom&t=glamorous)

[![puffy](https://user-images.githubusercontent.com/8309423/27024230-23fe9976-4f2c-11e7-854c-dfbd126997e3.png)](http://patorjk.com/software/taag/#p=display&f=Puffy&t=glamorous)

[![serif-cap](https://user-images.githubusercontent.com/8309423/27024236-2724f794-4f2c-11e7-900a-b6c27a571506.png)](http://patorjk.com/software/taag/#p=display&f=Serifcap&t=glamorous)

[![sub-zero](https://user-images.githubusercontent.com/8309423/27024240-2ae17d58-4f2c-11e7-885c-029652fd6f78.png)](http://patorjk.com/software/taag/#p=display&f=Sub-Zero&t=glamorous)

And thats how it might look:

![image](https://user-images.githubusercontent.com/8309423/27025357-909fcbdc-4f30-11e7-900e-a4d14c2d61b7.png)

**Comment by kentcdodds** [comment]
I love it! Let's do the one you had a screenshot of :+1: So awesome.

Maybe we could also invite them to contribute with an additional friendly message or something too!

**Comment by gillchristian** [comment]
What about something like this ?
![image](https://user-images.githubusercontent.com/8309423/27035564-2a468632-4f58-11e7-816a-428d62d57a0c.png)

[Here](http://jsbin.com/kecewiw/edit?js,console) is the JS Bin, please edit the messages as you like :smile:

**Comment by kentcdodds** [comment]
Oh, that's awesome! I totally love it! Can we make "GLAMOROUS" a gradient too? Let's make this happen. @paulmolluzzo, do you have a suggestion of where this would go? I'm thinking it could work the same way Google Analytics works :)

**Comment by gillchristian** [comment]
I tried and only the first line does get the gradient, the rest not and worse the are transparent. ¯\\\_(ツ)_/¯

Yes, we could add a script in the head that does this `console.log`'s.

**Comment by kentcdodds** [comment]
Cool, let's make a file like [this one](https://github.com/kentcdodds/glamorous-website/blob/master/components/google-analytics.js) and render it [here](https://github.com/kentcdodds/glamorous-website/blob/master/pages/_document/index.js#L66) :)

**Comment by kentcdodds** [comment]
This is awesome:

<img width="574" alt="screen shot 2017-06-12 at 10 29 52 am" src="https://user-images.githubusercontent.com/1500684/27044258-2629ab2c-4f5a-11e7-9b65-939efbbb072b.png">
